/* ================================================================
 * anime.js — 动漫角色库
 * 日本动漫与国产动漫分开存放；角色按性别拆分：
 *   男角色 → 男同区（Yaoi 模式），女角色 → 女同区（Yuri 模式）
 * 数据格式：A(中文名, 英文名, 年份, 男角色[], 女角色[])
 *   角色条目："danbooru风格标签:中文名"（如 "asuna:亚丝娜"）
 * 说明：静态站点无法收录全部动漫，本库为「经典+热门+冷门」精选
 *   集合并可无限扩充（见 README），角色均为成年作品或全年龄作品。
 * ================================================================ */
'use strict';

function A(zh, en, year, male, female) {
  const parse = (arr) => (arr || []).map(s => {
    const i = s.lastIndexOf(':');
    return i > 0 ? { t: s.slice(0, i), zh: s.slice(i + 1) } : { t: s, zh: s };
  });
  return { zh, en, year, male: parse(male), female: parse(female) };
}

const ANIME_DB = {
  /* ===================== 🇯🇵 日本动漫 ===================== */
  jp: [
    // ---- 1980s-90s 经典 ----
    A('机动战士高达0079', 'Mobile Suit Gundam', 1979, ['amuro_ray:阿姆罗·雷', 'char_aznable:夏亚·阿兹纳布尔'], ['sayla_mass:塞拉·玛斯', 'lalah_sune:拉拉·辛']),
    A('城市猎人', 'City Hunter', 1987, ['ryo_saeba:冴羽獠'], ['kaori_makimura:槙村香']),
    A('圣斗士星矢', 'Saint Seiya', 1986, ['seiya:星矢', 'shiryu:紫龙', 'hyoga:冰河', 'shun:瞬', 'ikki:一辉'], ['saori_kido:城户纱织']),
    A('龙珠', 'Dragon Ball', 1986, ['goku:孙悟空', 'krillin:克林', 'yamcha:饮茶'], ['bulma:布尔玛', 'chichi:琪琪']),
    A('龙珠Z', 'Dragon Ball Z', 1989, ['goku:孙悟空', 'vegeta:贝吉塔', 'gohan:孙悟饭', 'piccolo:比克'], ['bulma:布尔玛', 'chichi:琪琪', 'android_18:人造人18号']),
    A('乱马1/2', 'Ranma 1/2', 1989, ['ranma_saotome:早乙女乱马', 'ryoga_higashi:响良牙'], ['akane_tendo:天道茜', 'shampoo:珊璞']),
    A('樱桃小丸子', 'Chibi Maruko-chan', 1990, [], ['maruko_sakura:樱桃小丸子']),
    A('美少女战士', 'Sailor Moon', 1992, ['tuxedo_mask:夜礼服假面'], ['usagi_tsukino:月野兔', 'ami_mizuno:水野亚美', 'rei_hino:火野丽', 'makoto_kino:木野真琴', 'minako_aino:爱野美奈子']),
    A('蜡笔小新', 'Crayon Shin-chan', 1992, ['nohara_shinnosuke:野原新之助'], ['nohara_misae:野原美冴']),
    A('幽游白书', 'Yu Yu Hakusho', 1992, ['yusuke_urameshi:浦饭幽助', 'kurama:藏马', 'hiei:飞影', 'kuwabara_kazuma:桑原和真'], ['botan:牡丹', 'keiko_yukimura:雪村萤子']),
    A('灌篮高手', 'Slam Dunk', 1993, ['sakuragi_hanamichi:樱木花道', 'rukawa_kaede:流川枫', 'akagi_takenori:赤木刚宪', 'mitsui_hisashi:三井寿'], ['akagi_haruko:赤木晴子']),
    A('新世纪福音战士', 'Neon Genesis Evangelion', 1995, ['ikari_shinji:碇真嗣', 'nagisa_kaworu:渚薰', 'ikari_gendo:碇源堂'], ['ayanami_rei:绫波丽', 'sohryu_asuka_langley:明日香', 'katsuragi_misato:葛城美里']),
    A('攻壳机动队', 'Ghost in the Shell', 1995, ['batou:巴特'], ['kusanagi_motoko:草薙素子']),
    A('名侦探柯南', 'Detective Conan', 1996, ['edogawa_conan:江户川柯南', 'kudo_shinichi:工藤新一', 'kaitou_kid:怪盗基德'], ['mouri_ran:毛利兰', 'haibara_ai:灰原哀']),
    A('浪客剑心', 'Rurouni Kenshin', 1996, ['himura_kenshin:绯村剑心', 'sagara_sanosuke:相乐左之助'], ['kamiya_kaoru:神谷薫']),
    A('精灵宝可梦', 'Pokemon', 1997, ['satoshi:小智', 'takeshi:小刚'], ['kasumi:小霞', 'serena:莎莉娜', 'hikari:小光']),
    A('星际牛仔', 'Cowboy Bebop', 1998, ['spike_spiegel:斯派克·斯皮格尔', 'jet_black:杰特·布莱克'], ['faye_valentine:菲·瓦伦丁']),
    A('魔卡少女樱', 'Cardcaptor Sakura', 1998, ['li_syaoran:李小狼'], ['kinomoto_sakura:木之本樱', 'daidouji_tomoyo:大道寺知世']),
    A('哆啦A梦', 'Doraemon', 1979, ['nobi_nobita:野比大雄', 'doraemon:哆啦A梦'], ['minamoto_shizuka:源静香']),
    A('数码宝贝大冒险', 'Digimon Adventure', 1999, ['kamiya_taichi:八神太一', 'ishida_yamato:石田大和'], ['takenouchi_sora:武之内空', 'kamiya_hikari:八神光']),
    A('海贼王', 'One Piece', 1999, ['monkey_d_luffy:蒙奇·D·路飞', 'roronoa_zoro:罗罗诺亚·索隆', 'sanji:山治', 'portgas_d_ace:波特卡斯·D·艾斯'], ['nami:娜美', 'nico_robin:妮可·罗宾', 'boa_hancock:波雅·汉库克']),
    A('全职猎人', 'Hunter x Hunter', 1999, ['gon_freecss:小杰·富力士', 'killua_zoldyck:奇犽·揍敌客', 'kurapika:酷拉皮卡', 'leorio:雷欧力', 'hisoka:西索'], []),
    A('头文字D', 'Initial D', 1998, ['fujiwara_takumi:藤原拓海', 'takahashi_keisuke:高桥启介'], []),
    A('游戏王', 'Yu-Gi-Oh!', 2000, ['muto_yugi:武藤游戏', 'kaiba_seto:海马濑人', 'joey_wheeler:城之内克也'], ['mai_valentine:孔雀舞']),
    A('犬夜叉', 'Inuyasha', 2000, ['inuyasha:犬夜叉', 'sesshomaru:杀生丸', 'miroku:弥勒'], ['higurashi_kagome:日暮戈薇', 'sango:珊瑚', 'kikyo:桔梗']),
    A('火影忍者', 'Naruto', 2002, ['uzumaki_naruto:漩涡鸣人', 'uchiha_sasuke:宇智波佐助', 'hatake_kakashi:旗木卡卡西', 'uchiha_itachi:宇智波鼬'], ['haruno_sakura:春野樱', 'hyuga_hinata:日向雏田']),
    A('死神', 'Bleach', 2004, ['kurosaki_ichigo:黑崎一护', 'kuchiki_byakuya:朽木白哉', 'hitsugaya_toushirou:日番谷冬狮郎'], ['kuchiki_rukiya:朽木露琪亚', 'inoue_orihime:井上织姬', 'shihoin_yoruichi:四枫院夜一']),
    A('网球王子', 'Prince of Tennis', 2001, ['echizen_ryoma:越前龙马', 'tezuka_kunimitsu:手冢国光', 'fuji_syusuke:不二周助'], ['ryuzaki_sakuno:龙崎樱乃']),
    A('钢之炼金术师', 'Fullmetal Alchemist', 2003, ['elric_edward:爱德华·艾尔利克', 'elric_alphonse:阿尔冯斯·艾尔利克', 'mustang_roy:罗伊·马斯坦'], ['rockbell_winry:温莉·洛克贝尔', 'hawkeye_riza:莉莎·霍克艾']),
    A('银魂', 'Gintama', 2006, ['sakata_gintoki:坂田银时', 'shimura_shinpachi:志村新八', 'hijikata_toshiro:土方十四郎'], ['kagura:神乐', 'tsukuyo:月咏']),
    A('鲁邦三世', 'Lupin III', 1971, ['lupin_iii:鲁邦三世', 'jigen_daisuke:次元大介', 'goemon_ishikawa:石川五右卫门'], ['mine_fujiko:峰不二子']),
    // ---- 2000s ----
    A('灼眼的夏娜', 'Shakugan no Shana', 2005, ['sakai_yuji:坂井悠二'], ['shana:夏娜']),
    A('凉宫春日的忧郁', 'The Melancholy of Haruhi Suzumiya', 2006, ['kyon:阿虚'], ['suzumiya_haruhi:凉宫春日', 'nagato_yuki:长门有希', 'asahina_mikuru:朝比奈实玖瑠']),
    A('反叛的鲁路修', 'Code Geass', 2006, ['lelouch_lamperouge:鲁路修·兰佩路基', 'kururugi_suzaku:枢木朱雀'], ['c.c.:C.C.', 'stadtfeld_kallen:卡莲·修塔菲尔特']),
    A('死亡笔记', 'Death Note', 2006, ['yagami_light:夜神月', 'l:L', 'ryuk:硫克'], ['amane_misa:弥海砂']),
    A('寒蝉鸣泣之时', 'Higurashi no Naku Koro ni', 2006, ['maebara_keiichi:前原圭一'], ['ryuugu_rena:龙宫礼奈', 'sonozaki_mion:园崎魅音', 'houjou_satoko:北条沙都子', 'furude_rika:古手梨花']),
    A('黑执事', 'Black Butler', 2008, ['phantomhive_ciel:夏尔·凡多姆海恩', 'sebastian_michaelis:塞巴斯蒂安·米卡利斯'], ['midford_elizabeth:伊丽莎白·米德福特']),
    A('龙与虎', 'Toradora!', 2008, ['takasu_ryuuji:高须龙儿'], ['aisaka_taiga:逢坂大河', 'kushieda_minori:栉枝实乃梨']),
    A('狼与香辛料', 'Spice and Wolf', 2008, ['kraft_lawrence:克拉福·罗伦斯'], ['holo:赫萝']),
    A('魔法禁书目录', 'A Certain Magical Index', 2008, ['kamijou_touma:上条当麻'], ['index:茵蒂克丝', 'misaka_mikoto:御坂美琴']),
    A('夏目友人帐', 'Natsume Yuujinchou', 2008, ['natsume_takashi:夏目贵志'], []),
    A('出包王女', 'To LOVE-Ru', 2008, ['yuuki_rito:结城梨斗'], ['lala_satalin_deviluke:菈菈·撒塔琳·戴比路克', 'sairenji_haruna:西连寺春菜', 'deviluke_momo:梦梦·贝莉雅·戴比路克', 'golden_darkness:金色暗影']),
    A('纯情罗曼史', 'Junjo Romantica', 2008, ['takahashi_misaki:高桥美咲', 'usami_akihiko:宇佐见秋彦'], []),
    A('空之境界', 'Kara no Kyoukai', 2007, ['kokuto_mikiya:黑桐干也'], ['ryougi_shiki:两仪式']),
    A('CLANNAD', 'Clannad', 2007, ['okazaki_tomoya:冈崎朋也'], ['furukawa_nagisa:古河渚', 'sakagami_tomoyo:坂上智代', 'fujibayashi_kyou:藤林杏', 'ichinose_kotomi:一之濑琴美']),
    A('天元突破红莲螺岩', 'Gurren Lagann', 2007, ['simon:西蒙', 'kamina:卡米那'], ['littner_yoko:阳子·利特纳', 'nia:妮亚']),
    A('幸运星', 'Lucky Star', 2007, [], ['izumi_konata:泉此方', 'hiiragi_kagami:柊镜', 'hiiragi_tsukasa:柊司', 'takara_miyuki:高良美幸']),
    A('某科学的超电磁炮', 'A Certain Scientific Railgun', 2009, [], ['misaka_mikoto:御坂美琴', 'shirai_kuroko:白井黑子', 'saten_ruiko:佐天泪子', 'uiharu_kazari:初春饰利']),
    A('轻音少女', 'K-On!', 2009, [], ['hirasawa_yui:平泽唯', 'akiyama_mio:秋山澪', 'tainaka_ritsu:田井中律', 'kotobuki_tsumugi:琴吹䌷', 'nakano_azusa:中野梓']),
    A('化物语', 'Bakemonogatari', 2009, ['araragi_koyomi:阿良良木历'], ['senjougahara_hitagi:战场原黑仪', 'hachikuji_mayoi:八九寺真宵', 'kanbaru_suruga:神原骏河', 'sengoku_nadeko:千石抚子']),
    A('妖精的尾巴', 'Fairy Tail', 2009, ['dragneel_natsu:纳兹·多拉格尼尔', 'fullbuster_gray:格雷·佛尔帕斯塔'], ['heartfilia_lucy:露西·哈特菲利亚', 'scarlet_erza:艾尔扎·斯卡雷特']),
    A('轻声密语', 'Sasameki Koto', 2009, [], ['murase_sumika:村雨纯夏', 'kazehara_utsugi:风间汐']),
    A('Angel Beats!', 'Angel Beats!', 2010, ['otnashi_yuzuru:音无结弦'], ['nakamura_yuri:仲村由理', 'tachibana_kanade:立华奏']),
    A('无头骑士异闻录', 'Durarara!!', 2010, ['ryuugamine_mikado:龙之峰帝人', 'heiwajima_shizuo:平和岛静雄'], ['sonohara_anri:园原杏里', 'sturluson_celty:塞尔提·史特路尔森']),
    A('爆漫王', 'Bakuman', 2010, ['mashiro_moritaka:真城最高', 'takagi_akito:高木秋人'], ['azuki_miho:亚豆美保']),
    A('命运石之门', 'Steins;Gate', 2011, ['okabe_rintarou:冈部伦太郎'], ['makise_kurisu:牧濑红莉栖', 'shiina_mayuri:椎名真由理']),
    A('魔法少女小圆', 'Puella Magi Madoka Magica', 2011, [], ['kaname_madoka:鹿目圆', 'akemi_homura:晓美焰', 'miki_sayaka:美树沙耶加', 'sakura_kyouko:佐仓杏子', 'tomoe_mami:巴麻美']),
    A('未闻花名', 'Anohana', 2011, ['yadomi_jinta:宿海仁太'], ['honma_meiko:本间芽衣子', 'matsumoto_anaru:安城鸣子']),
    A('罪恶王冠', 'Guilty Crown', 2011, ['ooma_shu:樱满集'], ['yuzuriha_inori:楪祈']),
    A('摇曳百合', 'Yuru Yuri', 2011, [], ['akaza_akari:赤座灯里', 'toshinou_kyouko:岁纳京子', 'funami_yui:船见结衣', 'sugihara_chinatsu:杉浦绫乃']),
    A('未来日记', 'Mirai Nikki', 2011, ['amano_yukiteru:天野雪辉'], ['gasai_yuno:我妻由乃']),
    A('偶像大师', 'THE iDOLM@STER', 2011, [], ['amami_haruka:天海春香', 'kisaragi_chihaya:如月千早', 'hoshii_miki:星井美希', 'ganaha_hibiki:我那霸响']),
    A('世界第一初恋', 'Sekaiichi Hatsukoi', 2011, ['ono_ritsuka:小野寺律', 'takano_masamune:高野政宗'], []),
    A('中二病也要谈恋爱', 'Love, Chunibyo & Other Delusions', 2012, ['togashi_yuuta:富樫勇太'], ['takanashi_rikka:小鸟游六花']),
    A('刀剑神域', 'Sword Art Online', 2012, ['kirito:桐人', 'klein:克莱因'], ['asuna:亚丝娜', 'leafa:莉法', 'sinon:诗乃', 'yui:结衣']),
    A('高校DXD', 'High School DxD', 2012, ['hyoudou_issei:兵藤一诚'], ['rias_gremory:莉亚丝·吉蒙里', 'himejima_akeno:姬岛朱乃', 'asia_argento:爱西亚·阿基多']),
    A('黑子的篮球', 'Kuroko no Basket', 2012, ['kuroko_tetsuya:黑子哲也', 'kagami_taiga:火神大我', 'akashi_seijuurou:赤司征十郎'], []),
    A('冰菓', 'Hyouka', 2012, ['oreki_houtarou:折木奉太郎'], ['chitanda_eru:千反田爱瑠']),
    A('约会大作战', 'Date A Live', 2013, ['itsuka_shido:五河士道'], ['yatogami_tohka:夜刀神十香', 'tokisaki_kurumi:时崎狂三', 'yoshino:四糸乃']),
    A('进击的巨人', 'Attack on Titan', 2013, ['yeager_eren:艾伦·耶格尔', 'ackerman_levi:利威尔·阿克曼', 'arlet_armin:阿尔敏·阿莱特'], ['ackerman_mikasa:三笠·阿克曼', 'reiss_historia:希斯特利亚·雷伊斯']),
    A('记录的地平线', 'Log Horizon', 2013, ['shiroe:城惠'], ['akatsuki:晓']),
    A('Love Live!', 'Love Live! School Idol Project', 2013, [], ['kousaka_honoka:高坂穗乃果', 'sonoda_umi:园田海未', 'minami_kotori:南小鸟', 'ayase_eli:绚濑绘里', 'yazawa_nico:矢泽妮可', 'nishikino_maki:西木野真姬', 'toujou_nozomi:东条希', 'hoshizora_rin:星空凛', 'koizumi_hanayo:小泉花阳']),
    A('斩·赤红之瞳', 'Akame ga Kill!', 2014, ['tatsumi:塔兹米'], ['akame:赤瞳', 'mine:玛茵', 'esdeath:艾斯德斯']),
    A('排球少年', 'Haikyuu!!', 2014, ['hinata_shoyo:日向翔阳', 'kageyama_tobio:影山飞雄', 'oikawa_tooru:及川彻', 'nishinoya_yuu:西谷夕'], []),
    A('东京喰种', 'Tokyo Ghoul', 2014, ['kaneki_ken:金木研', 'arima_kishou:有马贵将'], ['kirishima_touka:雾岛董香', 'kamishiro_rize:神代利世']),
    A('寄生兽', 'Parasyte', 2014, ['izumi_shinichi:泉新一', 'migi:米奇'], ['murano_satomi:村野里美']),
    A('四月是你的谎言', 'Your Lie in April', 2014, ['arima_kousei:有马公生'], ['miyazono_kaori:宫园薰']),
    A('七大罪', 'The Seven Deadly Sins', 2014, ['meliodas:梅利奥达斯', 'ban:班'], ['elizabeth:伊丽莎白', 'diane:黛安']),
    A('Love Stage!!', 'Love Stage!!', 2014, ['sena_izumi:濑名泉水', 'ichijou_ryouma:一条龙马'], []),
    A('樱Trick', 'Sakura Trick', 2014, [], ['takayama_haruka:高山春香', 'sonoda_yuu:园田优']),
    A('月刊少女野崎君', 'Monthly Girls\' Nozaki-kun', 2014, ['nozaki_umetarou:野崎梅太郎'], ['sakura_chiyo:佐仓千代']),
    A('干物妹小埋', 'Himouto! Umaru-chan', 2015, ['doma_taihei:土间太平'], ['doma_umaru:土间埋', 'motoba_kirie:本场切绘']),
    A('一拳超人', 'One Punch Man', 2015, ['saitama:埼玉', 'genos:杰诺斯'], ['fubuki:吹雪', 'tatsumaki:战栗的龙卷']),
    A('食戟之灵', 'Food Wars!', 2015, ['yukihira_soma:幸平创真'], ['nakiri_erina:薙切绘里奈']),
    A('Re:从零开始的异世界生活', 'Re:Zero', 2016, ['natsuki_subaru:菜月昴'], ['emilia:艾米莉娅', 'rem:蕾姆', 'ram:拉姆', 'beatrice:碧翠丝']),
    A('为美好的世界献上祝福', 'KonoSuba', 2016, ['satou_kazuma:佐藤和真'], ['aqua:阿库娅', 'megumin:惠惠', 'darkness:达克妮丝']),
    A('我的英雄学院', 'My Hero Academia', 2016, ['midoriya_izuku:绿谷出久', 'bakugou_katsuki:爆豪胜己', 'todoroki_shouto:轰焦冻'], ['uraraka_ochako:丽日御茶子', 'asui_tsuyu:蛙吹梅雨']),
    A('灵能百分百', 'Mob Psycho 100', 2016, ['kageyama_shigeo:影山茂夫', 'reigen_arataka:灵幻新隆'], ['tsubomi:小蕾']),
    A('文豪野犬', 'Bungou Stray Dogs', 2016, ['nakajima_atsushi:中岛敦', 'dazai_osamu:太宰治', 'akutagawa_ryuunosuke:芥川龙之介'], ['yosano_akiko:与谢野晶子']),
    A('甲铁城的卡巴内瑞', 'Kabaneri of the Iron Fortress', 2016, ['ikoma:生驹'], ['mumei:无名']),
    A('Love Live! Sunshine!!', 'Love Live! Sunshine!!', 2016, [], ['takami_chika:高海千歌', 'sakurauchi_riko:樱内梨子', 'watanabe_you:渡边曜', 'tsushima_yoshiko:津岛善子', 'kurosawa_dia:黑泽黛雅', 'kurosawa_ruby:黑泽露比', 'kunikida_hanamaru:国木田花丸', 'ohara_mari:小原鞠莉', 'matsuura_kanan:松浦果南']),
    A('同級生', 'Doukyusei', 2016, ['kusakabe_hikaru:草壁光', 'sajou_ryou:佐条利人'], []),
    A('小林家的龙女仆', 'Miss Kobayashi\'s Dragon Maid', 2017, ['fafnir:法夫纳'], ['tohru:托尔', 'kanna_kamui:康娜卡姆依', 'kobayashi:小林']),
    A('少女终末旅行', 'Girls\' Last Tour', 2017, [], ['chito:千户', 'yuuri:尤莉']),
    A('埃罗芒阿老师', 'Eromanga Sensei', 2017, ['izumi_masamune:和泉正宗'], ['izumi_sagiri:和泉纱雾']),
    A('少女歌剧', 'Revue Starlight', 2018, [], ['aoi_karen:爱城华恋', 'kagura_hikari:神乐光']),
    A('赛马娘', 'Uma Musume Pretty Derby', 2018, [], ['special_week:特别周', 'silence_suzuka:无声铃鹿', 'toukaidou_teio:东海帝皇', 'mejiro_mcqueen:目白麦昆']),
    A('比宇宙更远的地方', 'A Place Further than the Universe', 2018, [], ['tamaki_mari:玉木麻理', 'kobuchizawa_shirase:小渊泽报濑', 'miyake_hinata:三宅日向', 'shiraishi_yuzuki:白石结月']),
    A('工作细胞', 'Cells at Work!', 2018, ['white_blood_cell:白细胞'], ['red_blood_cell:红血球', 'platelet:血小板']),
    A('摇曳露营', 'Laid-Back Camp', 2018, [], ['shima_rin:志摩凛', 'kagamihara_nadeshiko:各务原抚子']),
    A('DARLING in the FRANXX', 'Darling in the Franxx', 2018, ['hiro:广', 'goro:五郎'], ['zero_two:零二', 'ichigo:莓']),
    A('紫罗兰永恒花园', 'Violet Evergarden', 2018, ['bougainvillea_gilbert:吉尔伯特·布甘比利亚'], ['evergarden_violet:薇尔莉特·伊芙加登']),
    A('柑橘味香气', 'Citrus', 2018, [], ['aihara_yuzu:蓝原柚子', 'aihara_mei:蓝原芽衣']),
    A('终将成为你', 'Bloom Into You', 2018, [], ['koito_yuu:小糸侑', 'nanami_touko:七海灯子']),
    A('利兹与青鸟', 'Liz and the Blue Bird', 2018, [], ['kasuragi_nozomi:伞木希美', 'yoroizuka_mizore:铠冢霙']),
    A('鬼灭之刃', 'Demon Slayer: Kimetsu no Yaiba', 2019, ['kamado_tanjiro:灶门炭治郎', 'agatsuma_zenitsu:我妻善逸', 'hashibira_inosuke:嘴平伊之助', 'tomioka_giyuu:富冈义勇'], ['kamado_nezuko:灶门祢豆子', 'kanroji_mitsuri:甘露寺蜜璃', 'kochou_shinobu:蝴蝶忍']),
    A('五等分的新娘', 'The Quintessential Quintuplets', 2019, ['uesugi_futaro:上杉风太郎'], ['nakano_ichika:中野一花', 'nakano_nino:中野二乃', 'nakano_miku:中野三玖', 'nakano_yotsuba:中野四叶', 'nakano_itsuki:中野五月']),
    A('辉夜大小姐想让我告白', 'Kaguya-sama: Love is War', 2019, ['shirogane_miyuki:白银御行'], ['shinomiya_kaguya:四宫辉夜', 'fujiwara_chika:藤原千花']),
    A('约定的梦幻岛', 'The Promised Neverland', 2019, ['ray:雷', 'norman:诺曼'], ['emma:艾玛']),
    A('Dr.STONE 石纪元', 'Dr. Stone', 2019, ['ishigami_senku:石神千空', 'oouki_taiju:大树'], ['kohaku:琥珀']),
    A('街角魔族', 'The Demon Girl Next Door', 2019, [], ['shamiko:夏美子', 'chiyoda_momo:千代田桃']),
    A('天使降临到我身边', 'Wataten!: An Angel Flew Down to Me', 2019, [], ['hoshino_hinata:星野日向', 'shiwasaki_hana:白咲花', 'himesaka_noa:姬坂乃爱']),
    A('转生成史莱姆这档事', 'That Time I Got Reincarnated as a Slime', 2018, ['rimuru_tempest:利姆鲁·坦派斯特', 'benimaru:红丸'], ['shuna:朱菜', 'shion:紫苑']),
    A('盾之勇者成名录', 'The Rising of the Shield Hero', 2019, ['iwatani_naofumi:岩谷尚文'], ['raphtalia:拉芙塔莉雅']),
    A('哥布林杀手', 'Goblin Slayer', 2018, ['goblin_slayer:哥布林杀手'], ['priestess:女神官', 'high_elf_archer:高精灵弓手']),
    A('青春猪头少年不会梦到兔女郎学姐', 'Rascal Does Not Dream', 2018, ['azusagawa_sakuta:梓川咲太'], ['sakurajima_mai:樱岛麻衣']),
    A('地错 期待在地下城邂逅有错吗', 'DanMachi', 2015, ['cranel_bell:贝尔·克朗尼'], ['hestia:赫斯缇雅', 'wallenstein_ais:艾丝·华伦斯坦']),
    A('魔法少女网站', 'Magical Girl Site', 2018, [], ['aya_asagiri:朝雾彩', 'tsuyuno_yatsumura:八城月乃']),
    A('佐贺偶像是传奇', 'Zombie Land Saga', 2018, [], ['minamoto_sakura:源樱', 'nikaidou_saki:二阶堂咲', 'mizuno_ai:水野爱', 'konno_junko:绀野纯子', 'yugiri:夕雾', 'hoshikawa_lily:星川莉莉']),
    A('无职转生', 'Mushoku Tensei', 2021, ['greyrat_rudeus:鲁迪乌斯·格雷拉特'], ['migurdia_roxy:洛琪希·米格路迪亚', 'boreas_greyrat_eris:艾莉丝·伯雷亚斯·格雷拉特', 'sylphiette:希露菲叶特']),
    A('堀与宫村', 'Horimiya', 2021, ['miyamura_izumi:宫村伊澄'], ['hori_kyouko:堀京子']),
    A('奇蛋物语', 'Wonder Egg Priority', 2021, [], ['oto_ai:大户爱', 'awai_neiru:青沼宁瑠']),
    A('国王排名', 'Ranking of Kings', 2021, ['bojji:波吉', 'kage:卡克'], ['hiling:希琳']),
    A('影宅', 'Shadows House', 2021, [], ['kate:凯特', 'emilico:艾米莉可']),
    A('转生公主与天才千金的魔法革命', 'The Magical Revolution of the Reincarnated Princess', 2023, [], ['anisphia_wynn_palettia:安妮丝菲亚·温·帕雷提亚', 'euphyllia_magenta:尤菲莉亚·玛简塔']),
    A('间谍过家家', 'Spy x Family', 2022, ['forger_loid:黄昏/劳埃德·福杰'], ['forger_yor:约尔·福杰', 'forger_anya:阿尼亚·福杰']),
    A('更衣人偶坠入爱河', 'My Dress-Up Darling', 2022, ['gojo_wakana:五条新菜'], ['kitagawa_marin:喜多川海梦']),
    A('孤独摇滚！', 'Bocchi the Rock!', 2022, [], ['gotou_hitori:后藤一里', 'ichiji_nijika:伊地知虹夏', 'yamada_ryou:山田凉', 'kita_ikuyo:喜多郁代']),
    A('莉可丽丝', 'Lycoris Recoil', 2022, [], ['nishikigi_chisato:锦木千束', 'inoue_takina:井上泷奈']),
    A('电锯人', 'Chainsaw Man', 2022, ['denji:电次', 'hayakawa_aki:早川秋'], ['makima:玛奇玛', 'power:帕瓦', 'reze:蕾塞']),
    A('蓝色监狱', 'Blue Lock', 2022, ['isagi_yoichi:洁世一', 'bachira_meguru:蜂乐回', 'itoshi_rin:糸师凛'], []),
    A('彻夜之歌', 'Call of the Night', 2022, ['yamori_kou:夜守光'], ['nanakusa_nazuna:七草荠']),
    A('影之实力者', 'The Eminence in Shadow', 2022, ['kagenou_cid:希德·卡盖诺'], ['alpha:阿尔法', 'beta:贝塔', 'delta:德尔塔']),
    A('总之就是非常可爱', 'TONIKAWA: Over the Moon for You', 2020, ['yuzaki_nasa:由崎星空'], ['tsukuyomi_tsukasa:月读司']),
    A('佐佐木与宫野', 'Sasaki and Miyano', 2022, ['sasaki_shuumei:佐佐木秀鸣', 'miyano_yoshikazu:宫野由美'], []),
    A('异世界舅舅', 'Uncle from Another World', 2022, [], ['elf_(isekai_ojisan):傲娇精灵']),
    A('间谍教室', 'Spy Classroom', 2023, ['klaus:克劳斯'], ['lily:莉莉', 'annette:安妮特']),
    A('我推的孩子', 'Oshi no Ko', 2023, ['hoshino_aqua:星野爱久爱海'], ['hoshino_ai:星野爱', 'hoshino_ruby:星野瑠美衣', 'arima_kana:有马加奈']),
    A('药屋少女的呢喃', 'The Apothecary Diaries', 2023, ['jinshi:壬氏'], ['maomao:猫猫']),
    A('葬送的芙莉莲', 'Frieren: Beyond Journey\'s End', 2023, ['stark:修塔尔克', 'himmel:欣美尔'], ['frieren:芙莉莲', 'fern:费伦']),
    A('咒术回战', 'Jujutsu Kaisen', 2020, ['itadori_yuuji:虎杖悠仁', 'fushiguro_megumi:伏黑惠', 'gojo_satoru:五条悟', 'ryomen_sukuna:两面宿傩'], ['kugisaki_nobara:钉崎野蔷薇', 'zenin_maki:禅院真希']),
    A('无神世界的神明活动', 'KamiKatsu: Working for God in a Godless World', 2023, ['yukito:幸人'], ['ataraxia:阿塔拉西亚']),
    A('香格里拉·开拓异境', 'Shangri-La Frontier', 2023, ['hizutome_rakuro:阳务乐郎'], []),
    A('异世界迷宫开后宫', 'Isekai Meikyuu de Harem o', 2022, ['kaga_michio:加贺道夫'], ['roxanne:罗克珊', 'sherry:雪莉']),
    A('地。关于地球的运动', 'Orb: On the Movements of the Earth', 2024, ['rafal:拉法尔'], []),
    A('怪兽8号', 'Kaiju No. 8', 2024, ['hibino_kafka:日比野卡夫卡', 'ichikawa_reno:市川雷诺'], ['ashiro_mina:亚白米娜', 'shinomiya_kikoru:四之宫奇可露']),
    A('胆大党', 'Dandadan', 2024, ['takakura_ken:高仓健(厄卡伦)', 'jiji:吉吉'], ['ayase_momo:绫濑桃', 'shiratori_aira:白鸟爱罗']),
    A('失忆投捕', 'Oblivion Battery', 2024, ['kaname_kei:要圭', 'touma_tota:清峰叶流火'], []),
    A('败犬女主太多了！', 'Makeine: Too Many Losing Heroines!', 2024, ['nukumizu_kazuhiko:温水和彦'], ['yanami_anna:八奈见杏菜', 'yakishio_lemon:烧盐柠檬']),
    A('恰如细语般的恋歌', 'Whisper Me a Love Song', 2024, [], ['kino_himari:木野阳鞠', 'asagi_yori:朝凪依']),
    A('深夜Punch', 'Mayonaka Punch', 2024, [], ['masaki:真咲', 'yuki:雪']),
    A('魔王2099', 'Demon Lord 2099', 2024, ['veltol:贝尔托尔'], ['machina:玛奇娜']),
    A('地下城里的人们', 'Dungeon People', 2024, [], ['clay:克蕾', 'belle:贝儿']),
    A('2025年新番-胆大党第二季', 'Dandadan Season 2', 2025, ['takakura_ken:高仓健(厄卡伦)'], ['ayase_momo:绫濑桃', 'shiratori_aira:白鸟爱罗']),
    A('2025年新番-药屋少女的呢喃第二季', 'The Apothecary Diaries S2', 2025, ['jinshi:壬氏'], ['maomao:猫猫']),
    A('2025年新番-我推的孩子第三季', 'Oshi no Ko S3', 2025, ['hoshino_aqua:星野爱久爱海'], ['hoshino_ruby:星野瑠美衣', 'arima_kana:有马加奈']),
    A('2025年新番-鬼灭之刃无限城篇', 'Demon Slayer: Infinity Castle', 2025, ['kamado_tanjiro:灶门炭治郎', 'giyuu_tomioka:富冈义勇'], ['kamado_nezuko:灶门祢豆子']),
    A('2025年新番-一拳超人第三季', 'One Punch Man S3', 2025, ['saitama:埼玉', 'genos:杰诺斯'], ['tatsumaki:战栗的龙卷']),
    A('2026年-葬送的芙莉莲第二季', 'Frieren S2', 2026, ['stark:修塔尔克'], ['frieren:芙莉莲', 'fern:费伦']),
    A('2026年-迷宫饭第二季', 'Delicious in Dungeon S2', 2026, ['laios_touden:莱欧斯'], ['marcille_donato:玛露希尔']),
    A('2026年-转生史莱姆第四季', 'That Time I Got Reincarnated as a Slime S4', 2026, ['rimuru_tempest:利姆鲁'], ['shuna:朱菜', 'shion:紫苑']),
    A('2026年-蓝色监狱第三季', 'Blue Lock S3', 2026, ['isagi_yoichi:洁世一', 'itoshirin_rin:糸师凛'], []),
    A('2026年-孤独摇滚剧场版Re', 'Bocchi the Rock! Re:', 2026, [], ['gotou_hitori:后藤一里', 'kita_ikuyo:喜多郁代']),
  ],

  /* ===================== 🇨🇳 中国动漫 ===================== */
  cn: [
    A('黑猫警长', 'Black Cat Detective', 1984, ['heimao_jingzhang:黑猫警长'], []),
    A('葫芦兄弟', 'Calabash Brothers', 1986, ['dawa:大娃', 'erwa:二娃', 'sanwa:三娃', 'siwa:四娃', 'wuwa:五娃', 'liuwa:六娃', 'qiwa:七娃'], ['shejing:蛇精']),
    A('舒克贝塔', 'Shuke and Beita', 1989, ['shuke:舒克', 'beita:贝塔'], []),
    A('蓝猫淘气三千问', 'Blue Cat', 1999, ['lanmao:蓝猫', 'taoqi:淘气'], []),
    A('西游记（央视动画版）', 'Journey to the West (CCTV)', 1999, ['sun_wukong:孙悟空', 'tang_seng:唐僧', 'zhu_bajie:猪八戒', 'sha_seng:沙僧'], []),
    A('哪吒传奇', 'The Legend of Nezha', 2003, ['nezha:哪吒', 'xiaolongnv:小龙女'], []),
    A('大耳朵图图', 'Big Ears Tutu', 2004, ['tutu:图图'], []),
    A('喜羊羊与灰太狼', 'Pleasant Goat and Big Big Wolf', 2005, ['xi_yangyang:喜羊羊', 'hui_taitai:灰太狼', 'lan_yangyang:懒羊羊'], ['mei_yangyang:美羊羊', 'hong_taitai:红太狼']),
    A('猪猪侠', 'GG Bond', 2005, ['zhuzhuxia:猪猪侠'], []),
    A('虹猫蓝兔七侠传', 'The Story of the Seven Heroes', 2006, ['hongmao:虹猫', 'heixinhu:黑心虎'], ['lantu:蓝兔']),
    A('秦时明月', 'The Legend of Qin', 2007, ['tianming:天明', 'gai_nie:盖聂', 'wei_zhuang:卫庄'], ['duan_murong:端木蓉', 'xue_nv:雪女']),
    A('洛洛历险记', 'Luoluo', 2008, ['luoluo:洛洛'], []),
    A('果宝特攻', 'Fruit Force', 2009, [], []),
    A('熊出没', 'Boonie Bears', 2012, ['xiong_da:熊大', 'xiong_er:熊二', 'guang_touqiang:光头强'], []),
    A('画江湖之不良人', 'The Degenerates', 2014, ['li_xingyun:李星云', 'zhang_zifan:张子凡'], ['lu_linxuan:陆林轩', 'ji_rudan:姬如雪']),
    A('狐妖小红娘', 'Fox Spirit Matchmaker', 2015, ['dongfang_yuechu:东方月初', 'wang_quan_fugui:王权富贵'], ['tu_shansu:涂山苏苏', 'tu_shanya:涂山雅雅']),
    A('大鱼海棠', 'Big Fish & Begonia', 2016, ['qiu:湫', 'kun:鲲'], ['chun:椿']),
    A('一人之下', 'The Outcast', 2016, ['zhang_chulan:张楚岚', 'wang_ye:王也'], ['feng_baobao:冯宝宝']),
    A('镇魂街', 'Rakshasa Street', 2016, ['cao_yanbing:曹焱兵', 'cao_xuanliang:曹玄亮'], ['xia_ling:夏铃']),
    A('天行九歌', 'Tian Xing Jiu Ge', 2016, ['han_fei:韩非', 'zhang_liang:张良'], ['zi_nu:紫女', 'hong_lian:红莲']),
    A('武庚纪', 'Wu Geng Ji', 2016, ['wu_geng:武庚'], ['bai_cai:白菜']),
    A('全职高手', 'The King\'s Avatar', 2017, ['ye_xiu:叶修', 'huang_shaotian:黄少天', 'zhou_zekai:周泽楷'], ['su_mucheng:苏沐橙', 'tang_rou:唐柔']),
    A('斗破苍穹', 'Battle Through the Heavens', 2017, ['xiao_yan:萧炎'], ['xun_er:薰儿', 'yun_yun:云韵']),
    A('少年锦衣卫', 'The Young Imperial Guards', 2017, ['yuan_ling:袁凌'], ['jiu_gongzhu:九公主']),
    A('斗罗大陆', 'Soul Land', 2018, ['tang_san:唐三', 'dai_mubai:戴沐白'], ['xiao_wu:小舞', 'zhu_zhuqing:朱竹清', 'ning_rongrong:宁荣荣']),
    A('魔道祖师', 'Mo Dao Zu Shi', 2018, ['wei_wuxian:魏无羡', 'lan_wangji:蓝忘机', 'jiang_cheng:江澄', 'lan_xichen:蓝曦臣', 'jin_guangyao:金光瑶'], ['jiang_yanli:江厌离', 'wen_qing:温情']),
    A('星辰变', 'Stellar Transformations', 2018, ['qin_yu:秦羽'], []),
    A('刺客伍六七', 'Scissor Seven', 2018, ['wu_liuqi:伍六七', 'ji_dabao:鸡大保'], ['meihua_shisan:梅花十三']),
    A('少年歌行', 'The Young Brewmaster\'s Adventure', 2018, ['xiao_se:萧瑟', 'wuxin:无心'], []),
    A('非人哉', 'Non-Human', 2018, ['ao_lie:敖烈'], ['jiu_yue:九月']),
    A('灵笼', 'Ling Cage: Incarnation', 2019, ['mark:马克'], ['ran:冉冰']),
    A('汉化日记', 'Han Hua Ri Ji', 2019, [], ['su_motu:苏莫图']),
    A('罗小黑战记', 'The Legend of Luo Xiaohei', 2019, ['luo_xiaohei:罗小黑', 'wu_yan:无限'], []),
    A('哪吒之魔童降世', 'Ne Zha', 2019, ['nezha:哪吒', 'aobing:敖丙'], []),
    A('白蛇：缘起', 'White Snake', 2019, ['xu_xuan:许宣'], ['xiao_bai:小白', 'xiao_qing:小青']),
    A('大圣归来', 'Monkey King: Hero is Back', 2015, ['sun_wukong:孙悟空', 'jiangliuer:江流儿'], []),
    A('大理寺日志', 'White Cat Legend', 2020, ['li_bing:李饼', 'chen_shi:陈拾'], []),
    A('天官赐福', 'Heaven Official\'s Blessing', 2020, ['xie_lian:谢怜', 'hua_cheng:花城'], []),
    A('雾山五行', 'Fog Hill of Five Elements', 2020, ['wenren_yixuan:闻人翊悬'], []),
    A('穿书自救指南', 'Scumbag System', 2020, ['shen_qingqiu:沈清秋', 'luo_binghe:洛冰河'], []),
    A('仙王的日常生活', 'The Daily Life of the Immortal King', 2020, ['wang_ling:王令'], []),
    A('凡人修仙传', 'A Record of a Mortal\'s Journey to Immortality', 2020, ['han_li:韩立'], []),
    A('吞噬星空', 'Swallowed Star', 2020, ['luo_feng:罗峰'], []),
    A('一念永恒', 'A Will Eternal', 2020, ['bai_xiaochun:白小纯'], []),
    A('天宝伏妖录', 'Thousand Autumns', 2020, ['kong_hongjun:孔鸿俊'], []),
    A('时光代理人', 'Link Click', 2021, ['cheng_xiaoshi:程小时', 'lu_guang:陆光'], []),
    A('完美世界', 'Perfect World', 2021, ['shi_hao:石昊'], ['huo_linger:火灵儿', 'yue_chan:月婵']),
    A('眷思量', 'The Fated', 2021, ['jing_xuan:镜玄'], ['tu_li:屠丽']),
    A('白蛇2：青蛇劫起', 'White Snake 2: The Tribulation of the Green Snake', 2021, [], ['xiao_qing:小青', 'xiao_bai:小白']),
    A('雄狮少年', 'I Am What I Am', 2021, ['a_juan:阿娟'], []),
    A('姜子牙', 'Jiang Ziya', 2020, ['jiang_ziya:姜子牙'], []),
    A('长安三万里', 'Chang\'an', 2023, ['li_bai:李白', 'gao_shi:高适'], []),
    A('深海', 'Deep Sea', 2023, [], ['canhui:参宿']),
    A('三体', 'Three-Body', 2022, ['luo_ji:罗辑', 'shi_qiang:史强'], ['ye_wenjie:叶文洁']),
    A('我的三体', 'My Three Body', 2014, ['luo_ji:罗辑'], []),
    A('苍兰诀', 'Love Between Fairy and Devil', 2022, ['dongfang_qingcang:东方青苍'], ['xiao_lanhua:小兰花']),
    A('遮天', 'Shrouding the Heavens', 2023, ['ye_fan:叶凡'], []),
    A('仙逆', 'Renegade Immortal', 2023, ['wang_lin:王林'], ['li_muwan:李慕婉']),
    A('师兄啊师兄', 'Senior Brother', 2023, ['li_changshou:李长寿'], []),
    A('灵剑山', 'Spirit Sword Mountain', 2017, ['wang_wu:王陆'], []),
    A('妖神记', 'Tales of Demons and Gods', 2017, ['nie_li:聂离'], []),
    A('喜羊羊与灰太狼之筐出未来', 'Pleasant Goat Movie', 2022, ['xi_yangyang:喜羊羊'], ['mei_yangyang:美羊羊']),

    /* ---- 碧蓝航线 Azur Lane（国产手游，2019 年有日系动画版）----
     * 按阵营拆分存放（白鹰/皇家/重樱/铁血/东煌/北方联合/鸢尾/撒丁/META/塞壬/其他），
     * 收录全部可玩舰船（Kansen）及主要剧情/NPC 角色，男角色极少（指挥官/奥斯塔）放进男同区。
     * 角色标签统一使用 danbooru 风格带 (azur_lane) 消歧后缀。 */
    A('碧蓝航线-白鹰联邦', 'Azur Lane: Eagle Union', 2017, [], [
      'enterprise_(azur_lane):企业', 'hornet_(azur_lane):大黄蜂', 'yorktown_(azur_lane):约克城', 'wasp_(azur_lane):黄蜂',
      'intrepid_(azur_lane):无畏', 'ticonderoga_(azur_lane):提康德罗加', 'essex_(azur_lane):埃塞克斯', 'shangri-la_(azur_lane):香格里拉',
      'bataan_(azur_lane):巴丹', 'bunker_hill_(azur_lane):邦克山', 'kearsarge_(azur_lane):奇尔沙治',
      'yorktown_ii_(azur_lane):约克城II', 'hornet_ii_(azur_lane):大黄蜂II', 'hammann_ii_(azur_lane):哈曼II', 'laffey_ii_(azur_lane):拉菲II',
      'langley_(azur_lane):兰利', 'long_island_(azur_lane):长岛', 'bogue_(azur_lane):博格', 'ranger_(azur_lane):突击者',
      'independence_(azur_lane):独立', 'princeton_(azur_lane):普林斯顿', 'san_jacinto_(azur_lane):圣哈辛托',
      'saratoga_(azur_lane):萨拉托加', 'lexington_(azur_lane):列克星敦',
      'cleveland_(azur_lane):克利夫兰', 'denver_(azur_lane):丹佛', 'columbia_(azur_lane):哥伦比亚', 'montpelier_(azur_lane):蒙彼利埃',
      'birmingham_(azur_lane):伯明翰', 'biloxi_(azur_lane):比洛克西', 'houston_(azur_lane):休斯顿', 'st._louis_(azur_lane):圣路易斯(白鹰)',
      'atlanta_(azur_lane):亚特兰大', 'san_diego_(azur_lane):圣地亚哥', 'juneau_(azur_lane):朱诺(白鹰)', 'oakland_(azur_lane):奥克兰',
      'san_juan_(azur_lane):圣胡安', 'reno_(azur_lane):雷诺',
      'portland_(azur_lane):波特兰', 'indianapolis_(azur_lane):印第安纳波利斯',
      'north_carolina_(azur_lane):北卡罗来纳', 'washington_(azur_lane):华盛顿', 'south_dakota_(azur_lane):南达科他',
      'massachusetts_(azur_lane):马萨诸塞', 'alabama_(azur_lane):阿拉巴马', 'indiana_(azur_lane):印第安纳', 'new_jersey_(azur_lane):新泽西',
      'baltimore_(azur_lane):巴尔的摩', 'bremerton_(azur_lane):布雷默顿', 'san_francisco_(azur_lane):旧金山',
      'seattle_(azur_lane):西雅图', 'georgia_(azur_lane):佐治亚', 'kansas_(azur_lane):堪萨斯', 'minnesota_(azur_lane):明尼苏达',
      'alaska_(azur_lane):阿拉斯加',
      'fletcher_(azur_lane):弗莱彻', 'nicholas_(azur_lane):尼古拉斯', 'thatcher_(azur_lane):撒切尔', 'aylwin_(azur_lane):艾尔温',
      'spence_(azur_lane):斯彭斯', 'halsey_powell_(azur_lane):哈尔西·鲍威尔', 'kimberly_(azur_lane):金伯利',
      'charles_ausburne_(azur_lane):查尔斯·奥斯本', 'eldridge_(azur_lane):埃尔德里奇', 'benham_(azur_lane):本汉姆', 'maury_(azur_lane):莫里',
      'allen_m._sumner_(azur_lane):艾伦·萨姆纳', 'aulick_(azur_lane):奥利克', 'stephen_potter_(azur_lane):斯蒂芬·波特',
      'hammann_(azur_lane):哈曼', 'sims_(azur_lane):西姆斯', 'gridley_(azur_lane):格里德利', 'downes_(azur_lane):唐斯',
      'cassin_(azur_lane):卡辛', 'dewey_(azur_lane):杜威', 'laffey_(azur_lane):拉菲', 'helena_(azur_lane):海伦娜', 'vestal_(azur_lane):女灶神'
    ]),
    A('碧蓝航线-皇家', 'Azur Lane: Royal Navy', 2017, [], [
      'queen_elizabeth_(azur_lane):伊丽莎白女王', 'warspite_(azur_lane):厌战', 'royal_oak_(azur_lane):皇家橡树',
      'royal_sovereign_(azur_lane):皇家君主', 'valiant_(azur_lane):勇士', 'barham_(azur_lane):巴勒姆', 'malaya_(azur_lane):马来亚',
      'hood_(azur_lane):胡德', 'king_george_v_(azur_lane):乔治五世', 'prince_of_wales_(azur_lane):威尔士亲王',
      'duke_of_york_(azur_lane):约克公爵', 'howe_(azur_lane):豪', 'anson_(azur_lane):安森', 'monarch_(azur_lane):君主',
      'vanguard_(azur_lane):前卫', 'nelson_(azur_lane):纳尔逊', 'rodney_(azur_lane):罗德尼', 'renown_(azur_lane):声望',
      'repulse_(azur_lane):反击', 'glorious_(azur_lane):光荣', 'courageous_(azur_lane):勇敢', 'furious_(azur_lane):暴怒',
      'ark_royal_(azur_lane):皇家方舟', 'illustrious_(azur_lane):光辉', 'victorious_(azur_lane):胜利', 'formidable_(azur_lane):可畏',
      'indomitable_(azur_lane):不挠', 'implacable_(azur_lane):不倦', 'centaur_(azur_lane):半人马', 'albion_(azur_lane):阿尔比恩',
      'perseus_(azur_lane):珀耳修斯', 'unicorn_(azur_lane):独角兽', 'colossus_(azur_lane):巨人',
      'swiftsure_(azur_lane):迅捷', 'minotaur_(azur_lane):弥诺陶洛斯', 'neptune_(azur_lane):海王星', 'drake_(azur_lane):德雷克',
      'cheshire_(azur_lane):柴郡', 'plymouth_(azur_lane):普利茅斯', 'gibraltar_(azur_lane):直布罗陀',
      'belfast_(azur_lane):贝尔法斯特', 'edinburgh_(azur_lane):爱丁堡', 'sheffield_(azur_lane):谢菲尔德', 'newcastle_(azur_lane):纽卡斯尔',
      'glasgow_(azur_lane):格拉斯哥', 'jamaica_(azur_lane):牙买加', 'fiji_(azur_lane):斐济', 'ajax_(azur_lane):阿贾克斯',
      'achilles_(azur_lane):阿基里斯', 'exeter_(azur_lane):埃克塞特', 'york_(azur_lane):约克(皇家)', 'suffolk_(azur_lane):萨福克',
      'kent_(azur_lane):肯特', 'london_(azur_lane):伦敦', 'dorsetshire_(azur_lane):多塞特郡', 'norfolk_(azur_lane):诺福克',
      'dido_(azur_lane):黛朵', 'bellona_(azur_lane):贝洛娜', 'charybdis_(azur_lane):卡律布狄斯', 'hermione_(azur_lane):赫敏',
      'black_prince_(azur_lane):黑太子', 'sirius_(azur_lane):天狼星', 'leander_(azur_lane):利安得', 'arethusa_(azur_lane):阿瑞托莎',
      'galatea_(azur_lane):伽拉忒亚', 'penelope_(azur_lane):佩内洛普', 'aurora_(azur_lane):欧若拉',
      'javelin_(azur_lane):标枪', 'glowworm_(azur_lane):萤火虫', 'beagle_(azur_lane):小猎犬', 'bulldog_(azur_lane):斗牛犬',
      'amazon_(azur_lane):亚马逊', 'comet_(azur_lane):彗星', 'crescent_(azur_lane):新月(皇家)', 'cygnet_(azur_lane):天鹅',
      'foxhound_(azur_lane):猎狐犬', 'fortune_(azur_lane):命运女神', 'vampire_(azur_lane):吸血鬼', 'nubian_(azur_lane):努比亚人',
      'eskimo_(azur_lane):爱斯基摩人', 'musketeer_(azur_lane):火枪手', 'cossack_(azur_lane):哥萨克人', 'tatar_(azur_lane):鞑靼人',
      'maori_(azur_lane):毛利人', 'punjabi_(azur_lane):旁遮普人', 'hunter_(azur_lane):猎人',
      'janus_(azur_lane):雅努斯', 'jervis_(azur_lane):杰维斯', 'jupiter_(azur_lane):朱庇特', 'juno_(azur_lane):朱诺(皇家)',
      'acasta_(azur_lane):阿卡司塔', 'ardent_(azur_lane):热心', 'icarus_(azur_lane):伊卡洛斯', 'iron_duke_(azur_lane):铁公爵',
      'eagle_(azur_lane):鹰', 'hermes_(azur_lane):赫耳墨斯', 'little_belfast_(azur_lane):小贝法', 'little_illustrious_(azur_lane):小光辉'
    ]),
    A('碧蓝航线-重樱', 'Azur Lane: Sakura Empire', 2017, [], [
      'nagato_(azur_lane):长门', 'mutsu_(azur_lane):陆奥', 'yamato_(azur_lane):大和', 'musashi_(azur_lane):武藏',
      'shinano_(azur_lane):信浓', 'mikasa_(azur_lane):三笠', 'kongou_(azur_lane):金刚', 'hiei_(azur_lane):比叡',
      'haruna_(azur_lane):榛名', 'kirishima_(azur_lane):雾岛', 'amagi_(azur_lane):天城', 'kaga_(azur_lane):加贺',
      'akagi_(azur_lane):赤城', 'tosa_(azur_lane):土佐', 'izumo_(azur_lane):出云', 'suruga_(azur_lane):骏河',
      'kii_(azur_lane):纪伊', 'owari_(azur_lane):尾张', 'souryuu_(azur_lane):苍龙', 'hiryuu_(azur_lane):飞龙',
      'shoukaku_(azur_lane):翔鹤', 'zuikaku_(azur_lane):瑞鹤', 'taihou_(azur_lane):大凤', 'shouhou_(azur_lane):祥凤',
      'zuihou_(azur_lane):瑞凤', 'ryuujou_(azur_lane):龙骧', 'houshou_(azur_lane):凤翔', 'hiyou_(azur_lane):飞鹰',
      'junyou_(azur_lane):隼鹰', 'taiyou_(azur_lane):大鹰', 'chuyou_(azur_lane):冲鹰', 'unyou_(azur_lane):云鹰',
      'akashi_(azur_lane):明石', 'yuubari_(azur_lane):夕张', 'ayanami_(azur_lane):绫波', 'yuudachi_(azur_lane):夕立',
      'shigure_(azur_lane):时雨', 'yukikaze_(azur_lane):雪风', 'kagerou_(azur_lane):阳炎', 'shimakaze_(azur_lane):岛风',
      'naganami_(azur_lane):长波', 'takanami_(azur_lane):高波', 'fubuki_(azur_lane):吹雪', 'shirayuki_(azur_lane):白雪',
      'miyuki_(azur_lane):深雪', 'murakumo_(azur_lane):丛云', 'usugumo_(azur_lane):薄云', 'sazanami_(azur_lane):涟',
      'hatsuharu_(azur_lane):初春', 'hatsushimo_(azur_lane):初霜', 'wakaba_(azur_lane):若叶', 'ariake_(azur_lane):有明',
      'yuugure_(azur_lane):夕暮', 'shiratsuyu_(azur_lane):白露', 'murasame_(azur_lane):村雨', 'samidare_(azur_lane):五月雨',
      'suzukaze_(azur_lane):凉风', 'umikaze_(azur_lane):海风', 'yamakaze_(azur_lane):山风', 'kawakaze_(azur_lane):江风',
      'asashio_(azur_lane):朝潮', 'ooshio_(azur_lane):大潮', 'michishio_(azur_lane):满潮', 'arashio_(azur_lane):荒潮',
      'kasumi_(azur_lane):霞', 'kiso_(azur_lane):木曾', 'tama_(azur_lane):多摩', 'kitakami_(azur_lane):北上',
      'ooi_(azur_lane):大井', 'kuma_(azur_lane):球磨', 'nagara_(azur_lane):长良', 'isuzu_(azur_lane):五十铃',
      'yura_(azur_lane):由良', 'kinu_(azur_lane):鬼怒', 'abukuma_(azur_lane):阿武隈', 'sendai_(azur_lane):川内',
      'jintsuu_(azur_lane):神通', 'naka_(azur_lane):那珂', 'atago_(azur_lane):爱宕', 'takao_(azur_lane):高雄',
      'maya_(azur_lane):摩耶', 'choukai_(azur_lane):鸟海', 'myoukou_(azur_lane):妙高', 'nachi_(azur_lane):那智',
      'ashigara_(azur_lane):足柄', 'haguro_(azur_lane):羽黑', 'tone_(azur_lane):利根', 'chikuma_(azur_lane):筑摩',
      'mogami_(azur_lane):最上', 'mikuma_(azur_lane):三隈', 'suzuya_(azur_lane):铃谷', 'kumano_(azur_lane):熊野',
      'furutaka_(azur_lane):古鹰', 'kako_(azur_lane):加古', 'aoba_(azur_lane):青叶', 'kinugasa_(azur_lane):衣笠',
      'agano_(azur_lane):阿贺野', 'noshiro_(azur_lane):能代', 'yahagi_(azur_lane):矢矧', 'sakawa_(azur_lane):酒匂',
      'ibuki_(azur_lane):伊吹', 'azuma_(azur_lane):吾妻', 'hakuryuu_(azur_lane):白龙', 'kitakaze_(azur_lane):北风',
      'akizuki_(azur_lane):秋月', 'hatsuzuki_(azur_lane):初月', 'teruzuki_(azur_lane):照月', 'niizuki_(azur_lane):新月(重樱)',
      'wakatsuki_(azur_lane):若月', 'fuyutsuki_(azur_lane):冬月', 'harutsuki_(azur_lane):春月', 'yoizuki_(azur_lane):宵月',
      'shimotsuki_(azur_lane):霜月', 'suzutsuki_(azur_lane):凉月', 'hibiki_(azur_lane):响', 'akatsuki_(azur_lane):晓',
      'ikazuchi_(azur_lane):雷', 'inazuma_(azur_lane):电', 'kamikaze_(azur_lane):神风', 'matsukaze_(azur_lane):松风',
      'hatakaze_(azur_lane):旗风', 'asakaze_(azur_lane):朝风', 'harukaze_(azur_lane):春风', 'oite_(azur_lane):追风',
      'mutsuki_(azur_lane):睦月', 'kisaragi_(azur_lane):如月', 'yayoi_(azur_lane):弥生', 'uzuki_(azur_lane):卯月',
      'satsuki_(azur_lane):皋月', 'minazuki_(azur_lane):水无月', 'fumizuki_(azur_lane):文月', 'nagatsuki_(azur_lane):长月',
      'kikuzuki_(azur_lane):菊月', 'mikazuki_(azur_lane):三日月', 'mochizuki_(azur_lane):望月', 'ise_(azur_lane):伊势',
      'hyuuga_(azur_lane):日向', 'fusou_(azur_lane):扶桑', 'yamashiro_(azur_lane):山城', 'kashino_(azur_lane):樫野',
      'chitose_(azur_lane):千岁', 'chiyoda_(azur_lane):千代田', 'mizuho_(azur_lane):瑞穗', 'little_akagi_(azur_lane):小赤城'
    ]),
    A('碧蓝航线-铁血', 'Azur Lane: Ironblood', 2017, [], [
      'bismarck_(azur_lane):俾斯麦', 'tirpitz_(azur_lane):提尔比茨', 'friedrich_der_grosse_(azur_lane):腓特烈大帝',
      'gneisenau_(azur_lane):格奈森瑙', 'scharnhorst_(azur_lane):沙恩霍斯特', 'odin_(azur_lane):奥丁', 'siegfried_(azur_lane):齐格飞',
      'ulrich_von_hutten_(azur_lane):乌尔里希·冯·胡滕', 'prinz_rupprecht_(azur_lane):鲁普雷希特亲王', 'agir_(azur_lane):埃吉尔',
      'prinz_eugen_(azur_lane):欧根亲王', 'admiral_hipper_(azur_lane):希佩尔海军上将', 'bluecher_(azur_lane):布吕歇尔',
      'roon_(azur_lane):罗恩', 'mainz_(azur_lane):美因茨', 'weser_(azur_lane):威悉', 'elbe_(azur_lane):易北', 'jade_(azur_lane):雅德',
      'prinz_adalbert_(azur_lane):阿达尔贝特亲王', 'prinz_heinrich_(azur_lane):海因里希亲王', 'seydlitz_(azur_lane):塞德利茨',
      'luetzow_(azur_lane):吕措', 'yorck_(azur_lane):约克(铁血)', 'graf_spee_(azur_lane):斯佩伯爵海军上将',
      'admiral_scheer_(azur_lane):舍尔海军上将', 'deutschesland_(azur_lane):德意志', 'koenigsberg_(azur_lane):柯尼斯堡',
      'karlsruhe_(azur_lane):卡尔斯鲁厄', 'koeln_(azur_lane):科隆', 'leipzig_(azur_lane):莱比锡', 'nuernberg_(azur_lane):纽伦堡',
      'emden_(azur_lane):埃姆登', 'graf_zeppelin_(azur_lane):齐柏林伯爵', 'peter_strasser_(azur_lane):彼得·施特拉塞尔',
      'z1_(azur_lane):Z1', 'z2_(azur_lane):Z2', 'z23_(azur_lane):Z23', 'z24_(azur_lane):Z24', 'z25_(azur_lane):Z25',
      'z26_(azur_lane):Z26', 'z28_(azur_lane):Z28', 'z35_(azur_lane):Z35', 'z36_(azur_lane):Z36', 'z43_(azur_lane):Z43',
      'z46_(azur_lane):Z46', 'u-47_(azur_lane):U47', 'u-81_(azur_lane):U81', 'u-96_(azur_lane):U96', 'u-101_(azur_lane):U101',
      'u-110_(azur_lane):U110', 'u-410_(azur_lane):U410', 'u-522_(azur_lane):U522', 'u-556_(azur_lane):U556',
      'u-557_(azur_lane):U557', 'u-37_(azur_lane):U37'
    ]),
    A('碧蓝航线-东煌', 'Azur Lane: Dragon Empery', 2017, [], [
      'anshan_(azur_lane):鞍山', 'fushun_(azur_lane):抚顺', 'changchun_(azur_lane):长春', 'taiyuan_(azur_lane):太原',
      'ping_hai_(azur_lane):平海', 'ning_hai_(azur_lane):宁海', 'yat_sen_(azur_lane):逸仙', 'hai_tien_(azur_lane):海天',
      'hai_chi_(azur_lane):海圻', 'chao_ho_(azur_lane):肇和', 'ying_swei_(azur_lane):应瑞', 'chen_hai_(azur_lane):镇海',
      'harbin_(azur_lane):哈尔滨'
    ]),
    A('碧蓝航线-北方联合', 'Azur Lane: Northern Parliament', 2017, [], [
      'sovetskaya_rossiya_(azur_lane):苏维埃罗西亚', 'sovetskaya_belorussiya_(azur_lane):苏维埃白俄罗斯',
      'sovetskaya_soyuza_(azur_lane):苏维埃联盟', 'gangut_(azur_lane):甘古特', 'marat_(azur_lane):马拉特',
      'oktyabrskaya_revolyutsiya_(azur_lane):十月革命', 'avrora_(azur_lane):阿芙乐尔', 'pamiat_merkuria_(azur_lane):水星纪念',
      'kirov_(azur_lane):基洛夫', 'voroshilov_(azur_lane):伏罗希洛夫', 'maxim_gorky_(azur_lane):马克西姆·高尔基',
      'chapayev_(azur_lane):恰巴耶夫', 'kuybyshev_(azur_lane):古比雪夫', 'tallinn_(azur_lane):塔林',
      'kronshtadt_(azur_lane):喀琅施塔得', 'tashkent_(azur_lane):塔什干', 'grozny_(azur_lane):威严', 'gromky_(azur_lane):雷鸣',
      'gremyashchiy_(azur_lane):洪亮', 'soobrazitelny_(azur_lane):灵敏', 'stremitelny_(azur_lane):神速', 'ognevoy_(azur_lane):火力',
      'murmansk_(azur_lane):摩尔曼斯克', 'arkhangelsk_(azur_lane):阿尔汉格尔斯克'
    ]),
    A('碧蓝航线-自由鸢尾&维希教廷', 'Azur Lane: Iris Libre & Vichya', 2017, [], [
      'richelieu_(azur_lane):黎塞留', 'jean_bart_(azur_lane):让·巴尔', 'gascogne_(azur_lane):加斯科涅', 'joffre_(azur_lane):霞飞',
      'clemenceau_(azur_lane):克莱蒙梭', 'algerie_(azur_lane):阿尔及利亚', 'saint_louis_(azur_lane):圣路易斯(鸢尾)',
      'dunkerque_(azur_lane):敦刻尔克', 'strasbourg_(azur_lane):斯特拉斯堡', 'emile_bertin_(azur_lane):埃米尔·贝尔汀',
      'la_galissonniere_(azur_lane):拉·加利索尼埃', 'marseillaise_(azur_lane):马赛曲', 'jean_de_vienne_(azur_lane):让·德·维埃纳',
      'triomphant_(azur_lane):凯旋', 'l_indomptable_(azur_lane):倔强', 'l_audacieux_(azur_lane):鲁莽', 'le_malin_(azur_lane):恶毒',
      'le_fantasque_(azur_lane):空想', 'forbin_(azur_lane):福尔班', 'surcouf_(azur_lane):絮库夫', 'bearn_(azur_lane):贝亚恩',
      'brest_(azur_lane):布列斯特', 'mogador_(azur_lane):莫加多尔'
    ]),
    A('碧蓝航线-撒丁帝国', 'Azur Lane: Sardegna Empire', 2017, [], [
      'littorio_(azur_lane):利托里奥', 'vittorio_veneto_(azur_lane):维托里奥·维内托', 'roma_(azur_lane):罗马', 'impero_(azur_lane):帝国',
      'conte_di_cavour_(azur_lane):加富尔伯爵', 'giulio_cesare_(azur_lane):朱利奥·凯撒', 'andrea_doria_(azur_lane):安德烈亚·多利亚',
      'duilio_(azur_lane):杜伊利奥', 'zara_(azur_lane):扎拉', 'pola_(azur_lane):波拉', 'bolzano_(azur_lane):博尔扎诺',
      'trento_(azur_lane):特伦托', 'trieste_(azur_lane):的里雅斯特', 'gorizia_(azur_lane):戈里齐亚',
      'abruzzi_(azur_lane):阿布鲁齐公爵', 'garibaldi_(azur_lane):加里波第', 'aquila_(azur_lane):天鹰',
      'carabiniere_(azur_lane):步枪兵', 'nicoloso_da_recco_(azur_lane):尼科洛索·达·雷科', 'alfredo_oriani_(azur_lane):阿尔弗雷多·奥里亚尼',
      'vincenzo_gioberti_(azur_lane):文琴佐·焦贝蒂', 'maestrale_(azur_lane):西北风', 'libeccio_(azur_lane):西南风',
      'grecale_(azur_lane):格雷卡尔', 'scirocco_(azur_lane):西洛克', 'torricelli_(azur_lane):托里拆利',
      'leonardo_da_vinci_(azur_lane):列奥纳多·达·芬奇', 'guglielmo_marconi_(azur_lane):古列尔莫·马可尼'
    ]),
    A('碧蓝航线-META', 'Azur Lane: META', 2017, [], [
      'enterprise_meta_(azur_lane):企业META', 'akagi_meta_(azur_lane):赤城META', 'kaga_meta_(azur_lane):加贺META',
      'souryuu_meta_(azur_lane):苍龙META', 'hiryuu_meta_(azur_lane):飞龙META', 'repulse_meta_(azur_lane):反击META',
      'renown_meta_(azur_lane):声望META', 'queen_elizabeth_meta_(azur_lane):伊丽莎白女王META',
      'gneisenau_meta_(azur_lane):格奈森瑙META', 'scharnhorst_meta_(azur_lane):沙恩霍斯特META', 'takao_meta_(azur_lane):高雄META',
      'atago_meta_(azur_lane):爱宕META', 'ayanami_meta_(azur_lane):绫波META', 'javelin_meta_(azur_lane):标枪META',
      'laffey_meta_(azur_lane):拉菲META', 'z23_meta_(azur_lane):Z23META', 'memphis_meta_(azur_lane):孟菲斯META',
      'hornet_meta_(azur_lane):大黄蜂META', 'yorktown_meta_(azur_lane):约克城META', 'alabama_meta_(azur_lane):阿拉巴马META',
      'helena_meta_(azur_lane):海伦娜META', 'u-556_meta_(azur_lane):U556META', 'ark_royal_meta_(azur_lane):皇家方舟META',
      'vampire_meta_(azur_lane):吸血鬼META', 'hunter_meta_(azur_lane):猎人META'
    ]),
    A('碧蓝航线-塞壬', 'Azur Lane: Sirens', 2017, [], [
      'observer_(azur_lane):观察者', 'observer_zero_(azur_lane):观察者-零', 'tester_(azur_lane):测试者', 'purifier_(azur_lane):净化者',
      'purity_(azur_lane):清除者', 'compiler_(azur_lane):编译者'
    ]),
    A('碧蓝航线-其他', 'Azur Lane: Others', 2017, ['shikikan:指挥官', 'aoste_(azur_lane):奥斯塔'], [
      'shiranui_(azur_lane):不知火', 'anzeel_(azur_lane):安洁'
    ]),
  ],
};
