/* ================================================================
 * tags.js — 标签数据（含中文注释 / 推荐权重）与模型预设
 * T(t, nsfw, zh, recW)
 *   t    : 提示词标签（danbooru 风格，粘贴到 SD / NovelAI）
 *   nsfw : 露骨等级 0=普通 1=轻 2=中 3=重（随机生成按强度过滤）
 *   zh   : 中文注释（界面展示）
 *   recW : 推荐权重（点击标签时默认带上的权重，如 1.2；缺省=1）
 * 所有标签均以 18+ 成年角色为前提。
 * ================================================================ */
'use strict';

function T(t, nsfw, zh, recW) { return { t, nsfw, zh, w: recW }; }

/* ---------- 质量词（含中文注释） ---------- */
const QUALITY_TAGS = [
  // === 总体质量 ===
  T('masterpiece', 0, '杰作（顶级质量词）'),
  T('best quality', 0, '最佳质量'),
  T('amazing quality', 0, '惊人质量'),
  T('great quality', 0, '优秀质量'),
  T('good quality', 0, '良好质量'),
  T('high quality', 0, '高质量'),
  T('very high quality', 0, '极高画质'),
  T('finest quality', 0, '顶级画质'),
  T('incredible quality', 0, '不可思议的画质'),
  T('stellar quality', 0, '一流画质'),
  T('premium quality', 0, '优质画质'),
  // === 美学 / 构图 ===
  T('very aesthetic', 0, '非常美观（构图/色彩俱佳）'),
  T('aesthetic', 0, '美观'),
  T('absurdly beautiful', 0, '极致美丽'),
  T('gorgeous', 0, '华丽'),
  T('elegant', 0, '优雅'),
  T('stunning', 0, '惊艳'),
  T('breathtaking', 0, '令人窒息的美'),
  T('exquisite', 0, '精致绝伦'),
  T('glorious', 0, '壮丽'),
  T('lovely', 0, '可爱动人'),
  T('charming', 0, '迷人'),
  T('fantastic', 0, '极好'),
  T('splendid', 0, '绚丽'),
  T('opulent', 0, '奢华'),
  T('refined', 0, '精致考究'),
  T('masterful composition', 0, '大师级构图'),
  T('dynamic composition', 0, '动感构图'),
  T('balanced composition', 0, '均衡构图'),
  // === 分辨率 / 细节 ===
  T('absurdres', 0, '超分辨率画质（细节拉满）'),
  T('highres', 0, '高分辨率'),
  T('ultra-detailed', 0, '超精细细节'),
  T('extremely detailed', 0, '极度精细'),
  T('very detailed', 0, '非常精细'),
  T('intricate details', 0, '错综复杂的细节'),
  T('finely detailed', 0, '精细入微'),
  T('meticulously detailed', 0, '精心刻画的细节'),
  T('razor-sharp details', 0, '锐利细节'),
  T('micro details', 0, '微观细节'),
  T('detailed skin', 0, '精细皮肤纹理'),
  T('detailed eyes', 0, '精细眼部'),
  T('detailed face', 0, '精细面部'),
  T('detailed background', 0, '精细背景'),
  T('ornate background', 0, '华丽精致的背景'),
  T('intricate background', 0, '复杂的背景'),
  T('detailed clothing', 0, '精细服装'),
  T('detailed fabric', 0, '精细布料质感'),
  T('detailed water', 0, '精细水面'),
  T('detailed hair', 0, '精细发丝'),
  T('individual hair strands', 0, '根根分明的发丝'),
  T('hair detail', 0, '发丝细节'),
  // === 分辨率标签 ===
  T('8k wallpaper', 0, '8K 壁纸级画质'),
  T('6k', 0, '6K 分辨率'),
  T('4k', 0, '4K 分辨率'),
  T('UHD', 0, '超高清'),
  T('photorealistic', 0, '照片级写实'),
  T('hyperrealistic', 0, '超写实'),
  T('hyperdetailed', 0, '超精细'),
  // === 清晰度 / 对焦 ===
  T('sharp focus', 0, '锐利对焦'),
  T('crisp focus', 0, '清晰对焦'),
  T('perfect focus', 0, '完美对焦'),
  T('tack sharp', 0, '极其锐利'),
  T('clarity', 0, '高清晰度'),
  T('crystal clear', 0, '水晶般清澈'),
  // === 人体结构 ===
  T('perfect anatomy', 0, '完美人体结构'),
  T('perfect body', 0, '完美身材'),
  T('correct anatomy', 0, '正确的人体结构'),
  T('natural anatomy', 0, '自然的人体结构'),
  T('beautiful legs', 0, '美腿'),
  T('beautiful hands', 0, '美手'),
  T('perfect hands', 0, '完美手部（防畸形手）'),
  T('perfect fingers', 0, '完美手指'),
  T('detailed hands', 0, '精细手部'),
  T('beautiful face', 0, '美丽的脸'),
  T('perfect face', 0, '完美面部'),
  T('perfect eyes', 0, '完美眼睛'),
  T('beautiful detailed eyes', 0, '美丽精细的眼睛'),
  T('sparkling eyes', 0, '闪闪发光的眼睛'),
  T('detailed beautiful eyes', 0, '精细的美丽眼睛'),
  T('detailed pupils', 0, '精细的瞳孔'),
  // === 画风 / 风格 ===
  T('official art', 0, '官方立绘风格'),
  T('anime style', 0, '动漫风格'),
  T('illustration', 0, '插画风格'),
  T('digital painting', 0, '数字绘画'),
  T('digital illustration', 0, '数字插画'),
  T('concept art', 0, '概念艺术'),
  T('artstation', 0, 'Artstation 风格'),
  T('pixiv', 0, 'Pixiv 风格'),
  T('detailed illustration', 0, '精细插画'),
  T('sharp illustration', 0, '锐利插画'),
  T('painterly', 0, '绘画质感'),
  T('painting', 0, '画作质感'),
  T('watercolor (medium)', 0, '水彩风格'),
  T('cel shading', 0, '赛璐璐风格'),
  T('flat color', 0, '平涂'),
  T('lineart', 0, '线稿风格'),
  T('line art', 0, '线稿'),
  T('newest', 0, '最新画风（2024+）'),
  T('new', 0, '新画风'),
  // === 光影 ===
  T('cinematic lighting', 0, '电影级打光'),
  T('soft lighting', 0, '柔和光线'),
  T('delicate lighting', 0, '细腻光影'),
  T('beautiful lighting', 0, '唯美光线'),
  T('dramatic lighting', 0, '戏剧性打光'),
  T('studio lighting', 0, '影棚级打光'),
  T('rembrandt lighting', 0, '伦勃朗光'),
  T('three-point lighting', 0, '三点布光'),
  T('natural lighting', 0, '自然光线'),
  T('ambient lighting', 0, '环境光'),
  T('glowing light', 0, '发光光效'),
  T('luminescence', 0, '荧光效果'),
  T('rim light', 0, '轮廓光/边缘光'),
  T('backlighting', 0, '逆光'),
  T('volumetric lighting', 0, '体积光（丁达尔光效）'),
  T('god rays', 0, '耶稣光/光束'),
  T('caustics', 0, '焦散光（水面折射光纹）'),
  T('subsurface scattering', 0, '次表面散射（皮肤通透感）'),
  T('light particles', 0, '光粒子'),
  T('lens light', 0, '镜头光线'),
  T('bright', 0, '明亮'),
  // === 色彩 ===
  T('warm colors', 0, '暖色调'),
  T('cool colors', 0, '冷色调'),
  T('vivid colors', 0, '鲜艳色彩'),
  T('vibrant colors', 0, '活力色彩'),
  T('rich colors', 0, '浓郁色彩'),
  T('deep colors', 0, '深邃色彩'),
  T('pastel colors', 0, '粉彩柔和色调'),
  T('muted colors', 0, '低饱和柔色'),
  T('monochrome', 0, '单色调'),
  T('high contrast', 0, '高对比度'),
  T('colorful', 0, '多彩'),
  T('iridescent', 0, '虹彩色'),
  T('gradient', 0, '渐变色'),
  T('sunset colors', 0, '日落色彩'),
  T('golden hour', 0, '黄金时刻色调'),
  // === 天气 / 环境 ===
  T('sunlight', 0, '阳光'),
  T('moonlight', 0, '月光'),
  T('starlight', 0, '星光'),
  T('rainy', 0, '雨天'),
  T('snowing', 0, '下雪'),
  T('foggy', 0, '雾气朦胧'),
  T('wind', 0, '微风'),
  T('underwater', 0, '水下场景'),
  T('night sky', 0, '夜空'),
  T('aurora', 0, '极光'),
  // === 氛围元素 ===
  T('cherry blossoms', 0, '樱花（氛围元素）'),
  T('petals', 0, '花瓣飘落'),
  T('falling petals', 0, '落英缤纷'),
  T('leaves', 0, '树叶'),
  T('autumn leaves', 0, '红叶/秋叶'),
  T('sparkles', 0, '闪闪光点'),
  T('glitter', 0, '亮片'),
  T('sparkle', 0, '星芒光点'),
  T('particles', 0, '粒子/光尘'),
  T('dust particles', 0, '浮尘粒子'),
  T('light dust', 0, '光尘'),
  T('embers', 0, '余烬/火星'),
  T('fireflies', 0, '萤火虫'),
  T('raindrops', 0, '雨滴'),
  T('water drops', 0, '水珠'),
  T('water splash', 0, '水花飞溅'),
  T('frost', 0, '霜花'),
  T('ice crystals', 0, '冰晶'),
  T('rainbow', 0, '彩虹'),
  T('butterflies', 0, '蝴蝶'),
  // === 镜头 / 摄影效果 ===
  T('bokeh', 0, '背景虚化光斑'),
  T('lens flare', 0, '镜头光晕'),
  T('depth of field', 0, '景深'),
  T('motion blur', 0, '动态模糊'),
  T('tilt-shift', 0, '移轴摄影效果'),
  T('wide-angle lens', 0, '广角镜头'),
  T('macro', 0, '微距镜头'),
  T('telephoto', 0, '长焦镜头'),
  T('film grain', 0, '胶片颗粒感'),
  T('chromatic aberration', 0, '色差效果'),
  T('vignette', 0, '暗角效果'),
  // === 画质增强 ===
  T('HDR', 0, '高动态范围'),
  T('anatomically correct', 0, '解剖学正确'),
  T('emotionless', 0, '无表情（冷酷感）'),
  T('serene', 0, '宁静祥和'),
  T('tranquil', 0, '恬静'),
  T('ethereal', 0, '空灵缥缈'),
  T('dreamy', 0, '梦幻'),
  T('surreal', 0, '超现实'),
  T('dark theme', 0, '暗色主题'),
  T('light theme', 0, '亮色主题'),
  T('fantasy', 0, '奇幻风格'),
  T('sci-fi', 0, '科幻风格'),
];

/* ---------- 共享分类：发型 / 发色 / 视角 ---------- */
const HAIR_STYLES = [
  T('short hair', 0, '短发'),
  T('medium hair', 0, '中长发'),
  T('long hair', 0, '长发'),
  T('very long hair', 0, '超长发'),
  T('bob cut', 0, '波波头（齐耳短发）'),
  T('hime cut', 0, '公主切（姬发式）'),
  T('twintails', 0, '双马尾'),
  T('low twintails', 0, '低双马尾'),
  T('ponytail', 0, '单马尾'),
  T('side ponytail', 0, '侧马尾'),
  T('braided ponytail', 0, '编辫马尾'),
  T('single braid', 0, '单辫子'),
  T('twin braids', 0, '双辫子'),
  T('braided hair', 0, '编发'),
  T('cornrows', 0, '贴头辫（编发纹）'),
  T('dreadlocks', 0, '脏辫'),
  T('pigtails', 0, '双扎发（低双马尾团）'),
  T('drill hair', 0, '螺旋卷发（钻头卷）'),
  T('ahoge', 0, '呆毛'),
  T('hair between eyes', 0, '眉间发丝'),
  T('bangs', 0, '刘海'),
  T('blunt bangs', 0, '齐刘海'),
  T('side bangs', 0, '侧分刘海'),
  T('swept bangs', 0, '斜刘海'),
  T('curtain bangs', 0, '八字刘海（中分垂帘）'),
  T('sidelocks', 0, '鬓角发'),
  T('parted bangs', 0, '中分刘海'),
  T('center parted hair', 0, '中分'),
  T('side parted hair', 0, '偏分'),
  T('undercut', 0, '渐变剃边发'),
  T('buzz cut', 0, '寸头'),
  T('crew cut', 0, '平头'),
  T('mohawk', 0, '莫西干头'),
  T('messy hair', 0, '凌乱头发'),
  T('spiky hair', 0, '刺猬头'),
  T('slicked-back hair', 0, '大背头'),
  T('wavy hair', 0, '波浪卷'),
  T('curly hair', 0, '卷发'),
  T('straight hair', 0, '直发'),
  T('fluffy hair', 0, '蓬松头发'),
  T('voluminous hair', 0, '丰盈浓密头发'),
  T('layered hair', 0, '层次剪'),
  T('hair bun', 0, '发髻'),
  T('double bun', 0, '双发髻'),
  T('topknot', 0, '丸子头'),
  T('odango', 0, '团子头（双丸子）'),
  T('chignon', 0, '低发髻（法式发髻）'),
  T('hair up', 0, '盘发'),
  T('half updo', 0, '半扎发'),
  T('hair down', 0, '散发'),
];

const HAIR_COLORS = [
  T('black hair', 0, '黑发'),
  T('brown hair', 0, '棕发'),
  T('light brown hair', 0, '浅棕发'),
  T('chestnut hair', 0, '栗色发'),
  T('auburn hair', 0, '赤褐发'),
  T('blonde hair', 0, '金发'),
  T('dirty blonde hair', 0, '暗金发'),
  T('platinum blonde hair', 0, '铂金发'),
  T('ash blonde hair', 0, '亚麻金发'),
  T('golden hair', 0, '金黄发'),
  T('yellow hair', 0, '黄发'),
  T('white hair', 0, '白发'),
  T('silver hair', 0, '银发'),
  T('grey hair', 0, '灰发'),
  T('blue hair', 0, '蓝发'),
  T('light blue hair', 0, '浅蓝发'),
  T('dark blue hair', 0, '深蓝发'),
  T('navy blue hair', 0, '藏青发'),
  T('aqua hair', 0, '水蓝发'),
  T('teal hair', 0, '青绿发'),
  T('cyan hair', 0, '青色发'),
  T('sky blue hair', 0, '天蓝发'),
  T('green hair', 0, '绿发'),
  T('light green hair', 0, '浅绿发'),
  T('mint green hair', 0, '薄荷绿发'),
  T('dark green hair', 0, '深绿发'),
  T('red hair', 0, '红发'),
  T('orange hair', 0, '橙发'),
  T('crimson hair', 0, '绯红发'),
  T('scarlet hair', 0, '猩红发'),
  T('pink hair', 0, '粉发'),
  T('light pink hair', 0, '浅粉发'),
  T('hot pink hair', 0, '桃粉发'),
  T('magenta hair', 0, '品红发'),
  T('purple hair', 0, '紫发'),
  T('violet hair', 0, '紫罗兰发'),
  T('lavender hair', 0, '薰衣草紫发'),
  T('lilac hair', 0, '丁香紫发'),
  T('multicolored hair', 0, '多色发'),
  T('two-tone hair', 0, '双色发'),
  T('gradient hair', 0, '渐变发色'),
  T('ombre hair', 0, '渐层染发'),
  T('streaked hair', 0, '挑染'),
  T('rainbow hair', 0, '彩虹发'),
];

const VIEW_TAGS = [
  T('POV', 0, '第一人称视角', 1.2),
  T('first-person view', 0, '主观视角（带入感强）', 1.1),
  T('selfie', 0, '自拍视角'),
  T('mirror shot', 0, '镜中拍摄'),
  T('from above', 0, '俯视'),
  T('bird\'s-eye view', 0, '鸟瞰视角'),
  T('from below', 0, '仰视'),
  T('worm\'s-eye view', 0, '虫瞰视角（极低仰角）'),
  T('low angle', 0, '低机位'),
  T('high angle', 0, '高机位'),
  T('dutch angle', 0, '倾斜镜头（荷兰角）'),
  T('from behind', 0, '从背后拍摄'),
  T('from front', 0, '正面拍摄'),
  T('from side', 0, '侧面拍摄'),
  T('side view', 0, '侧视图'),
  T('back view', 0, '背面视角'),
  T('front view', 0, '正面视角'),
  T('profile', 0, '侧脸轮廓'),
  T('three-quarter view', 0, '四分之三侧面'),
  T('over-the-shoulder', 0, '过肩镜头'),
  T('close-up', 0, '特写', 1.1),
  T('extreme close-up', 0, '大特写', 1.2),
  T('face focus', 0, '面部聚焦'),
  T('eye close-up', 0, '眼部特写'),
  T('lips close-up', 0, '唇部特写'),
  T('hand close-up', 0, '手部特写'),
  T('upper body', 0, '上半身'),
  T('waist-up', 0, '半身（腰部以上）'),
  T('lower body', 0, '下半身'),
  T('waist-down', 0, '腰部以下'),
  T('full body', 0, '全身'),
  T('medium shot', 0, '中景'),
  T('cowboy shot', 0, '牛仔镜头（大腿以上）'),
  T('wide shot', 0, '远景/全景'),
  T('long shot', 0, '远镜头'),
  T('establishing shot', 0, '环境定场镜头'),
  T('looking at viewer', 0, '看向观众'),
  T('looking away', 0, '视线移开'),
  T('looking back', 0, '回头看向'),
  T('looking up', 0, '抬头看'),
  T('looking down', 0, '低头看'),
  T('eye contact', 0, '眼神接触'),
  T('gaze at viewer', 0, '凝视观众'),
  T('dynamic angle', 0, '动态机位'),
  T('action shot', 0, '动作抓拍'),
  T('zoomed in', 0, '镜头拉近'),
  T('ultra wide angle', 0, '超广角'),
  T('fisheye', 0, '鱼眼镜头'),
];

/* ---------- 共享分类：审查与码（步兵/骑兵） ---------- */
const CENSOR_TAGS = [
  T('uncensored', 0, '无码（步兵：无马赛克，全露出）', 1.2),
  T('censored', 0, '有码（骑兵：带审查打码）'),
  T('censor', 0, '审查（打码总称）'),
  T('mosaic censoring', 0, '马赛克打码', 1.1),
  T('bar censor', 0, '条形打码（黑条）', 1.1),
  T('blur censor', 0, '模糊打码', 1.1),
  T('censor bar', 0, '审查条'),
  T('censor bar over genitals', 0, '生殖器上的审查条', 1.2),
  T('censor bar over breasts', 0, '胸部上的审查条', 1.1),
  T('censor bar over nipples', 0, '乳首上的审查条', 1.1),
  T('partial censoring', 0, '局部打码（只遮部分部位）', 1.1),
  T('partially uncensored', 0, '局部无码（露一半遮一半）', 1.2),
  T('pixelated genitals', 0, '生殖器像素化', 1.2),
  T('pixelated breasts', 0, '胸部像素化'),
  T('pixelated nipples', 0, '乳首像素化'),
  T('genital censoring', 0, '生殖器打码', 1.1),
  T('breast censoring', 0, '胸部打码'),
  T('nipple censoring', 0, '乳首打码'),
  T('censored genitals', 0, '被码遮住的生殖器'),
  T('censored nipples', 0, '被码遮住的乳首'),
  T('mosaic over genitals', 0, '生殖器上的马赛克'),
  T('mosaic over nipples', 0, '乳首上的马赛克'),
  T('text censoring', 0, '文字遮盖（贴字/贴纸）'),
  T('no text censoring', 0, '无文字遮盖'),
  T('light censoring', 0, '轻度打码（小码）'),
  T('heavy censoring', 0, '重度打码（大码/全遮）'),
  T('uncensored version', 0, '无码版（画面未经审查处理）'),
];

/* ---------- 共享分类：性质（攻受性） ---------- */
const NATURE_TAGS = [
  T('seme', 0, '攻（上位·主导方）', 1.1),
  T('uke', 0, '受（下位·被主导方）', 1.1),
  T('switch', 0, '可攻可受（互攻互受）', 1.1),
  T('dominant', 0, '支配系（强势方）', 1.1),
  T('submissive', 0, '顺从系（弱势方）', 1.1),
  T('top', 0, '上位（Top）'),
  T('bottom', 0, '下位（Bottom）'),
  T('versatile', 0, '全能型（攻受皆可）'),
  T('strong seme', 0, '强攻（气场压制）', 1.1),
  T('gentle seme', 0, '温柔攻', 1.1),
  T('cool seme', 0, '冷面攻'),
  T('sadistic seme', 0, '抖S攻（施虐倾向）', 1.2),
  T('yandere seme', 0, '病娇攻', 1.1),
  T('tsundere seme', 0, '傲娇攻'),
  T('playful seme', 0, '玩世不恭的攻'),
  T('strong uke', 0, '强受（倔强不服软）'),
  T('shy uke', 0, '害羞受'),
  T('tsundere uke', 0, '傲娇受', 1.1),
  T('yandere uke', 0, '病娇受', 1.2),
  T('masochistic uke', 0, '抖M受（受虐倾向）', 1.2),
  T('teary uke', 0, '泪眼汪汪的受', 1.1),
  T('tomboy', 0, 'T 系（帅气攻气，女同向）', 1.1),
  T('butch', 0, '铁T（硬朗攻，女同向）'),
  T('femme', 0, 'P 系（娇柔受，女同向）', 1.1),
  T('soft butch', 0, '软T（中性偏柔，女同向）'),
  T('androgynous', 0, '中性气质（雌雄莫辨）'),
  T('masculine', 0, '阳刚气质'),
  T('feminine', 0, '柔美气质'),
  T('teasing bottom', 0, '撩人的下位'),
];

/* ---------- 默认负面词 ---------- */
const NEGATIVE_DEFAULT = [
  'lowres', 'bad anatomy', 'bad hands', 'text', 'error', 'missing fingers', 'extra digit',
  'fewer digits', 'cropped', 'worst quality', 'low quality', 'normal quality', 'jpeg artifacts',
  'signature', 'watermark', 'username', 'blurry', 'artist name', 'deformed', 'bad proportions',
  'extra limbs', 'cloned face', 'disfigured', 'gross proportions', 'malformed limbs', 'long neck',
  'mutated hands', 'fused fingers', 'bad feet', 'extra arms', 'extra legs', 'duplicate',
  'morphed', 'boring', 'plain background', 'out of frame', 'low contrast', 'oversaturated',
  'underexposed', 'overexposed', '3d', 'cgi', 'sketch', 'bad eyes', 'bad nipples',
  'bad pussy', 'bad cock', 'bad pubic hair', 'ugly', 'disgusting', 'gross', 'censored',
  'mosaic', 'bar censor', 'blur censor',
].join(', ');

/* ---------- 模型预设 ----------
 * extraQuality : 加入随机池的模型特色质量词
 * specialTags  : 显示为「🎯 模型专属」分类的标签
 * negative     : 切换到该模型时的默认负面词
 * params       : 推荐生成参数（sampler/steps/cfg/size/clip）
 */
const MODEL_PRESETS = {
  generic: {
    label: '🌀 通用 (SD / NovelAI)',
    desc: '适用于大多数动漫模型与 NovelAI；使用经典 masterpiece 质量词。',
    extraQuality: [],
    specialTags: [],
    negative: NEGATIVE_DEFAULT,
    params: { sampler: 'Euler a', steps: 28, cfg: 7, size: '832x1216', clip: 2 },
  },
  illustrious: {
    label: '🎨 Illustrious XL',
    desc: 'Danbooru 标签体系 SDXL 模型：核心是 score 评分词 + source/rating/year 标签，评分词能显著提升质量。分辨率建议 832x1216，Clip skip 2。',
    extraQuality: ['score_9', 'score_8_up', 'score_7_up', 'score_6_up'],
    specialTags: [
      T('score_9', 0, '9 分（最高质量评分，必带）', 1.1),
      T('score_8_up', 0, '8 分及以上', 1.1),
      T('score_7_up', 0, '7 分及以上', 1.1),
      T('score_6_up', 0, '6 分及以上（兜底评分）'),
      T('score_5_up', 0, '5 分及以上'),
      T('source:anime', 0, '来源：动漫'),
      T('source:cartoon', 0, '来源：卡通'),
      T('source:videogame', 0, '来源：游戏'),
      T('rating:explicit', 2, '评级：成人（NSFW 内容请加此标签）', 1.1),
      T('rating:questionable', 1, '评级：擦边'),
      T('rating:safe', 0, '评级：安全（全年龄）'),
      T('year:2024', 0, '画风年份 2024'),
      T('year:2025', 0, '画风年份 2025'),
    ],
    negative: 'score_4, score_5, score_6, ' + NEGATIVE_DEFAULT,
    params: { sampler: 'DPM++ 2M Karras', steps: 28, cfg: 7, size: '832x1216', clip: 2 },
  },
  janima: {
    label: '✨ JANIMA',
    desc: '2.9B Anima 系模型（SDXL 架构）：经典质量词 + danbooru 标签，支持 BREAK 分段符把提示词分组，多人物/多要素时很有用。质量词见「✨ 质量词」分类。',
    extraQuality: ['very aesthetic', 'absurdres', 'newest'],
    specialTags: [
      T('BREAK', 0, '分段符：把提示词分成几组，避免标签互相污染', 1),
    ],
    negative: NEGATIVE_DEFAULT,
    params: { sampler: 'Euler a', steps: 28, cfg: 7, size: '832x1216', clip: 2 },
  },
  nova: {
    label: '🚀 Nova Anime AM',
    desc: 'Crody 出品的 Anima 系动漫模型（Illustrious 血统）：score 评分词 + danbooru 标签，NSFW 表现优秀。',
    extraQuality: ['score_9', 'score_8_up', 'score_7_up', 'source:anime', 'year:2024'],
    specialTags: [
      T('score_9', 0, '9 分（最高质量评分，必带）', 1.1),
      T('score_8_up', 0, '8 分及以上', 1.1),
      T('score_7_up', 0, '7 分及以上'),
      T('source:anime', 0, '来源：动漫'),
      T('rating:explicit', 2, '评级：成人（NSFW 内容请加此标签）', 1.1),
      T('year:2024', 0, '画风年份 2024'),
      T('year:2025', 0, '画风年份 2025'),
    ],
    negative: 'score_4, score_5, score_6, ' + NEGATIVE_DEFAULT,
    params: { sampler: 'DPM++ 2M Karras', steps: 30, cfg: 6.5, size: '832x1216', clip: 2 },
  },
};

/* ---------- 模式与标签库 ---------- */
const MODES = {
  gay: {
    label: '男同 (Yaoi)',
    categories: [
      {
        key: 'model', label: '🎯 模型专属',
        tags: [], // 运行时按所选模型注入
      },
      {
        key: 'base', label: '🧑 角色基础',
        tags: [
          T('1boy', 0, '1 个男性角色'),
          T('2boys', 0, '2 个男性角色'),
          T('adult male', 0, '成年男性'),
          T('mature male', 0, '成熟男性'),
          T('young adult male', 0, '青年男性（成年）'),
          T('bara', 0, '熊系/筋肉系（Bara 风格）', 1.1),
          T('bear', 0, '熊系壮男'),
          T('twink', 0, '少年系纤细男（成年）'),
          T('otoko no ko', 0, '伪娘（男の娘）'),
          T('femboy', 0, '女装男/药娘风'),
          T('crossdressing', 0, '异装/女装'),
          T('kemonomimi', 0, '兽耳'),
          T('muscular male', 0, '肌肉男'),
          T('slim male', 0, '清瘦男性'),
          T('tall male', 0, '高个子男性'),
          T('short male', 0, '矮个子男性'),
          T('androgynous male', 0, '中性美少年'),
          T('handsome male', 0, '英俊男性'),
          T('beautiful male', 0, '美型男性'),
          T('older man', 0, '年长男性（成年）'),
          T('size difference', 0, '体型差（最萌身高差）', 1.1),
        ],
      },
      {
        key: 'nature', label: '🧭 性质（攻受性 1/0）', tags: NATURE_TAGS,
      },
      {
        key: 'body', label: '💪 体型与身体',
        tags: [
          T('muscular', 0, '肌肉发达'),
          T('toned', 0, '线条紧致'),
          T('lean', 0, '精瘦'),
          T('athletic', 0, '运动型身材'),
          T('broad shoulders', 0, '宽肩'),
          T('thick thighs', 0, '大腿粗壮'),
          T('muscular arms', 0, '肌肉手臂'),
          T('defined abs', 0, '腹肌分明'),
          T('six-pack abs', 0, '六块腹肌'),
          T('pecs', 0, '胸肌'),
          T('hairy chest', 0, '胸毛'),
          T('chest hair', 0, '胸部体毛'),
          T('body hair', 0, '体毛'),
          T('sweat', 0, '汗水'),
          T('glistening skin', 0, '皮肤泛光（汗湿）'),
          T('tanned skin', 0, '晒黑皮肤'),
          T('fair skin', 0, '白皙皮肤'),
          T('dark skin', 0, '深色皮肤'),
          T('large penis', 2, '大丁丁', 1.2),
          T('thick penis', 2, '粗丁丁', 1.2),
          T('long penis', 2, '长丁丁', 1.2),
          T('average penis', 2, '普通尺寸丁丁'),
          T('uncircumcised', 2, '未割包皮', 1.1),
          T('circumcised', 2, '割过包皮', 1.1),
          T('erect penis', 2, '勃起状态', 1.1),
          T('semi-erect', 2, '半勃起'),
          T('veiny penis', 2, '青筋暴起的丁丁'),
          T('pre-cum', 2, '前液（前列腺液）', 1.1),
          T('cum', 3, '精液', 1.2),
          T('pubic hair', 0, '阴毛'),
          T('trimmed pubic hair', 0, '修剪过的阴毛'),
          T('hairy legs', 0, '腿毛'),
          T('bubble butt', 1, '翘臀', 1.1),
          T('plump butt', 1, '丰满臀部', 1.1),
          T('firm butt', 1, '紧实臀部'),
          T('muscular back', 0, '肌肉背'),
          T('v-line', 0, '人鱼线'),
          T('adonis belt', 0, '阿多尼斯线（下腹V线）'),
          T('muscular thighs', 0, '肌肉大腿'),
        ],
      },
      {
        key: 'clothing', label: '👕 服装与脱衣',
        tags: [
          T('shirtless', 0, '赤膊/不穿上衣'),
          T('topless', 1, '上身赤裸'),
          T('naked', 2, '全裸', 1.1),
          T('nude', 2, '裸体', 1.1),
          T('fully nude', 2, '完全赤裸', 1.1),
          T('underwear', 1, '内衣'),
          T('boxer briefs', 1, '平角内裤'),
          T('briefs', 1, '三角内裤'),
          T('boxer shorts', 1, '四角短裤'),
          T('jockstrap', 1, '丁字运动护裆（Jockstrap）', 1.1),
          T('speedo', 0, '竞速泳裤'),
          T('fundoshi', 0, '兜裆布'),
          T('school uniform', 0, '校服'),
          T('gakuran', 0, '学兰（日式男校服）'),
          T('suit', 0, '西装'),
          T('dress shirt', 0, '衬衫'),
          T('unbuttoned shirt', 1, '解开纽扣的衬衫', 1.1),
          T('rolled-up sleeves', 0, '卷起袖子'),
          T('tie', 0, '领带'),
          T('tie loose', 1, '领带松垮', 1.1),
          T('tank top', 0, '背心'),
          T('muscle shirt', 0, '无袖紧身背心'),
          T('blazer', 0, '西装外套'),
          T('vest', 0, '马甲'),
          T('sweater', 0, '毛衣'),
          T('turtleneck', 0, '高领毛衣'),
          T('cardigan', 0, '开衫'),
          T('leather jacket', 0, '皮夹克'),
          T('denim jacket', 0, '牛仔外套'),
          T('bomber jacket', 0, '飞行夹克'),
          T('trench coat', 0, '风衣'),
          T('hoodie', 0, '连帽卫衣'),
          T('apron', 0, '围裙'),
          T('maid outfit', 1, '女仆装'),
          T('skirt', 1, '裙子'),
          T('panties', 2, '内裤（女式）', 1.1),
          T('lingerie', 2, '情趣内衣', 1.1),
          T('thigh-high socks', 1, '过膝袜'),
          T('stockings', 1, '长筒袜'),
          T('garter belt', 1, '吊袜带'),
          T('suspenders', 0, '背带裤背带'),
          T('shorts', 0, '短裤'),
          T('jeans', 0, '牛仔裤'),
          T('cargo pants', 0, '工装裤'),
          T('sweatpants', 0, '运动长裤'),
          T('tracksuit', 0, '运动服套装'),
          T('basketball uniform', 0, '篮球服'),
          T('baseball uniform', 0, '棒球服'),
          T('swim trunks', 0, '泳裤'),
          T('workout clothes', 0, '健身服'),
          T('towel', 0, '毛巾'),
          T('yukata', 0, '浴衣'),
          T('kimono', 0, '和服'),
          T('wet clothes', 1, '湿透的衣服', 1.1),
          T('transparent clothes', 2, '透明衣物', 1.2),
          T('half-undressed', 2, '脱到一半', 1.1),
          T('pants down', 2, '裤子褪下', 1.1),
          T('shirt off', 1, '脱掉上衣'),
          T('glasses', 0, '眼镜'),
          T('choker', 1, '颈环'),
          T('earrings', 0, '耳环'),
          T('necklace', 0, '项链'),
          T('gloves', 0, '手套'),
          T('fingerless gloves', 0, '露指手套'),
          T('arm warmers', 0, '臂套'),
          T('cap', 0, '鸭舌帽'),
          T('beanie', 0, '针织帽'),
          T('headband', 0, '发带'),
        ],
      },
      {
        key: 'action', label: '🔥 动作与体位',
        tags: [
          T('kissing', 1, '接吻'),
          T('french kiss', 1, '法式深吻', 1.1),
          T('making out', 1, '热吻缠绵'),
          T('embracing', 1, '拥抱'),
          T('hugging', 1, '相拥'),
          T('hugging from behind', 1, '背后抱', 1.1),
          T('cuddling', 1, '依偎'),
          T('groping', 2, '摸胸/乱摸', 1.1),
          T('fondling', 2, '爱抚'),
          T('nipple play', 2, '玩弄乳头', 1.1),
          T('handjob', 2, '手交', 1.2),
          T('mutual masturbation', 2, '互相打飞机', 1.2),
          T('frotting', 2, '丁丁互磨', 1.2),
          T('intercrural sex', 2, '股间摩擦（腿交）', 1.2),
          T('grinding', 2, '磨蹭/摩擦', 1.1),
          T('dry humping', 2, '隔着衣服摩擦', 1.1),
          T('lap dance', 2, '膝上舞'),
          T('strip tease', 1, '脱衣舞'),
          T('blowjob', 3, '口交', 1.2),
          T('fellatio', 3, '口交（正式词）', 1.1),
          T('deepthroat', 3, '深喉', 1.3),
          T('facefuck', 3, '颜面骑乘（口爆脸）', 1.3),
          T('rimming', 3, '舔菊', 1.2),
          T('anilingus', 3, '舔肛（正式词）', 1.1),
          T('anal fingering', 3, '手指插入后穴', 1.2),
          T('prostate massage', 3, '前列腺按摩', 1.2),
          T('anal sex', 3, '肛交', 1.2),
          T('doggy style', 3, '后入式', 1.2),
          T('missionary', 3, '传教士体位（正常位）', 1.1),
          T('cowgirl', 3, '骑乘位', 1.2),
          T('reverse cowgirl', 3, '反向骑乘位', 1.2),
          T('riding', 3, '骑乘', 1.1),
          T('mating press', 3, '种付姿势（折腿压腰）', 1.3),
          T('spooning sex', 3, '侧卧式（汤匙式）'),
          T('sixty-nine', 3, '69 式互口', 1.2),
          T('standing sex', 3, '站立式'),
          T('wall sex', 3, '壁咚式做爱', 1.1),
          T('shower sex', 3, '浴室做爱', 1.1),
          T('sex', 3, '性行为（总括）', 1.2),
          T('penetration', 3, '插入', 1.2),
          T('creampie', 3, '中出（体内射精）', 1.3),
          T('internal cumshot', 3, '体内射精', 1.2),
          T('external cumshot', 3, '体外射精', 1.1),
          T('cum on face', 3, '颜射', 1.2),
          T('cum on body', 3, '射在身上', 1.1),
          T('swallowing', 3, '吞精', 1.2),
          T('cumdrip', 3, '精液滴落', 1.2),
          T('multiple cumshots', 3, '多次射精', 1.2),
          T('cumshot', 3, '射精（总括）', 1.2),
          T('orgasm', 3, '高潮', 1.2),
          T('multiple orgasms', 3, '多次高潮', 1.2),
          T('dripping cum', 3, '精液流下', 1.2),
        ],
      },
      {
        key: 'expression', label: '😳 表情与状态',
        tags: [
          T('ahegao', 2, '阿黑颜（失神高潮脸）', 1.2),
          T('blush', 1, '脸红'),
          T('embarrassed', 1, '害羞'),
          T('flustered', 1, '慌乱'),
          T('aroused', 1, '兴奋/动情'),
          T('lustful', 2, '充满欲望', 1.1),
          T('lewd smile', 2, '淫笑', 1.1),
          T('grinning', 1, '咧嘴笑'),
          T('smirk', 1, '坏笑'),
          T('closed eyes', 1, '闭眼'),
          T('tears', 2, '流泪', 1.1),
          T('crying in pleasure', 3, '爽哭', 1.2),
          T('drooling', 3, '流口水', 1.2),
          T('tongue out', 2, '伸舌头', 1.1),
          T('panting', 2, '喘息', 1.1),
          T('breathing heavily', 2, '粗重呼吸', 1.1),
          T('heart eyes', 1, '爱心眼'),
          T('needy', 2, '饥渴难耐', 1.1),
          T('pleading', 2, '恳求'),
          T('moaning', 3, '呻吟', 1.2),
          T('seductive smile', 1, '挑逗微笑'),
          T('surprised', 1, '惊讶'),
          T('shy', 1, '腼腆'),
          T('dripping sweat', 1, '汗流浃背'),
        ],
      },
      {
        key: 'env', label: '🌍 场景环境',
        tags: [
          T('bedroom', 0, '卧室'),
          T('bed', 0, '床上'),
          T('hotel room', 0, '酒店房间'),
          T('love hotel', 0, '情趣酒店'),
          T('bathroom', 0, '浴室'),
          T('shower', 0, '淋浴间'),
          T('onsen', 0, '温泉'),
          T('public bath', 0, '公共浴池'),
          T('sauna', 0, '桑拿'),
          T('locker room', 0, '更衣室/储物间'),
          T('gym', 0, '健身房'),
          T('office', 0, '办公室'),
          T('classroom', 0, '教室'),
          T('library', 0, '图书馆'),
          T('dressing room', 0, '试衣间'),
          T('changing room', 0, '更衣室'),
          T('alley', 0, '小巷'),
          T('beach', 0, '海滩'),
          T('pool', 0, '泳池'),
          T('forest', 0, '森林'),
          T('rooftop', 0, '天台'),
          T('car', 0, '车内'),
          T('night', 0, '夜晚'),
          T('sunset', 0, '黄昏'),
          T('indoor', 0, '室内'),
          T('outdoor', 0, '室外'),
          T('japanese room', 0, '日式房间'),
          T('tatami', 0, '榻榻米'),
          T('desk', 0, '办公桌'),
          T('steam', 0, '蒸汽/雾气'),
          T('oil', 0, '油（油亮皮肤）'),
        ],
      },
      {
        key: 'props', label: '🧰 道具与细节',
        tags: [
          T('condom', 2, '安全套', 1.1),
          T('lube', 3, '润滑液', 1.2),
          T('sex toy', 3, '情趣玩具', 1.2),
          T('vibrator', 3, '按摩棒', 1.2),
          T('collar', 2, '项圈', 1.1),
          T('leash', 2, '牵引绳', 1.1),
          T('handcuffs', 2, '手铐'),
          T('blindfold', 2, '眼罩'),
          T('rope', 3, '绳索（绳缚）', 1.2),
          T('mirror', 1, '镜子'),
          T('bed sheets', 0, '床单'),
          T('pillows', 0, '枕头'),
          T('champagne', 0, '香槟'),
          T('rose petals', 0, '玫瑰花瓣'),
          T('candlelight', 0, '烛光'),
        ],
      },
      { key: 'censor', label: '🚫 审查与码（步兵/骑兵）', tags: CENSOR_TAGS },
      { key: 'hair', label: '💇 发型', tags: HAIR_STYLES },
      { key: 'haircolor', label: '🎨 发色', tags: HAIR_COLORS },
      { key: 'view', label: '📷 视角与镜头', tags: VIEW_TAGS },
      { key: 'quality', label: '✨ 质量词', tags: QUALITY_TAGS },
    ],
  },

  lesbian: {
    label: '女同 (Yuri)',
    categories: [
      {
        key: 'model', label: '🎯 模型专属',
        tags: [], // 运行时按所选模型注入
      },
      {
        key: 'base', label: '👩 角色基础',
        tags: [
          T('1girl', 0, '1 个女性角色'),
          T('2girls', 0, '2 个女性角色'),
          T('yuri', 0, '百合（女同题材）', 1.1),
          T('adult woman', 0, '成年女性'),
          T('mature woman', 0, '成熟女性'),
          T('young adult woman', 0, '青年女性（成年）'),
          T('milf', 0, '熟女（人妻风，成年）', 1.1),
          T('elegant woman', 0, '优雅女性'),
          T('beautiful woman', 0, '美丽女性'),
          T('cute girl', 0, '可爱女孩'),
          T('tall woman', 0, '高挑女性'),
          T('short woman', 0, '娇小女性'),
          T('curvy woman', 0, '丰满曲线女性'),
          T('slender woman', 0, '纤细女性'),
          T('androgynous woman', 0, '中性风女性'),
          T('kemonomimi', 0, '兽耳'),
          T('elf', 0, '精灵'),
          T('dark-skinned woman', 0, '深肤色女性'),
          T('fair-skinned woman', 0, '白肤女性'),
          T('glasses', 0, '眼镜'),
        ],
      },
      {
        key: 'nature', label: '🧭 性质（攻受性 1/0）', tags: NATURE_TAGS,
      },
      {
        key: 'body', label: '💃 体型与身体',
        tags: [
          T('large breasts', 0, '大胸', 1.1),
          T('huge breasts', 0, '巨乳', 1.2),
          T('medium breasts', 0, '中等胸部'),
          T('small breasts', 0, '小胸'),
          T('flat chest', 0, '平胸'),
          T('perky breasts', 0, '挺拔胸部'),
          T('round breasts', 0, '圆润胸部'),
          T('firm breasts', 0, '紧实胸部'),
          T('big areolas', 1, '大乳晕', 1.1),
          T('pink nipples', 1, '粉色乳头', 1.1),
          T('dark nipples', 1, '深色乳头', 1.1),
          T('erect nipples', 1, '乳头挺立', 1.1),
          T('curvy', 0, '凹凸有致'),
          T('hourglass figure', 0, '沙漏型身材'),
          T('narrow waist', 0, '细腰'),
          T('wide hips', 0, '宽胯'),
          T('thick thighs', 0, '大腿丰满'),
          T('plump thighs', 0, '肉感大腿'),
          T('long legs', 0, '长腿'),
          T('soft skin', 0, '柔软肌肤'),
          T('glowing skin', 0, '皮肤光泽'),
          T('tan lines', 0, '晒痕'),
          T('slim', 0, '苗条'),
          T('petite', 0, '娇小'),
          T('muscular woman', 0, '肌肉感女性'),
          T('abs', 0, '腹肌'),
          T('sweat', 0, '汗水'),
          T('glistening skin', 0, '皮肤泛光（汗湿）'),
          T('wet body', 1, '湿身'),
        ],
      },
      {
        key: 'clothing', label: '👗 服装与脱衣',
        tags: [
          T('naked', 2, '全裸', 1.1),
          T('nude', 2, '裸体', 1.1),
          T('topless', 2, '上身赤裸', 1.1),
          T('fully nude', 2, '完全赤裸', 1.1),
          T('underwear', 1, '内衣'),
          T('bra and panties', 1, '胸罩+内裤'),
          T('matching lingerie', 1, '成套内衣'),
          T('lace lingerie', 1, '蕾丝内衣', 1.1),
          T('babydoll', 1, '娃娃裙式睡衣'),
          T('teddy', 1, '连体情趣内衣'),
          T('corset', 1, '束腰'),
          T('garter belt', 1, '吊袜带'),
          T('thigh-high stockings', 1, '过膝袜'),
          T('fishnet stockings', 1, '渔网袜', 1.1),
          T('pantyhose', 1, '连裤袜'),
          T('school uniform', 0, '校服'),
          T('sailor uniform', 0, '水手服'),
          T('maid outfit', 1, '女仆装'),
          T('nurse outfit', 1, '护士装'),
          T('office lady', 0, '办公室女郎（OL）'),
          T('suit', 0, '西装'),
          T('dress shirt', 0, '衬衫'),
          T('blouse', 0, '女士衬衫'),
          T('camisole', 0, '吊带背心'),
          T('tube top', 0, '抹胸'),
          T('crop top', 0, '露脐短上衣'),
          T('tank top', 0, '背心'),
          T('sweater', 0, '毛衣'),
          T('cardigan', 0, '开衫'),
          T('hoodie', 0, '连帽卫衣'),
          T('denim jacket', 0, '牛仔外套'),
          T('leather jacket', 0, '皮夹克'),
          T('blazer', 0, '小西装外套'),
          T('vest', 0, '马甲'),
          T('trench coat', 0, '风衣'),
          T('coat', 0, '大衣'),
          T('dress', 0, '连衣裙'),
          T('evening gown', 0, '晚礼服'),
          T('wedding dress', 0, '婚纱', 1.1),
          T('qipao', 0, '旗袍', 1.1),
          T('cheongsam', 0, '旗袍（英文名）'),
          T('hanfu', 0, '汉服'),
          T('kimono', 0, '和服'),
          T('yukata', 0, '浴衣'),
          T('skirt', 0, '裙子'),
          T('pleated skirt', 0, '百褶裙'),
          T('pencil skirt', 0, '包臀裙'),
          T('mini skirt', 0, '超短裙'),
          T('short skirt', 0, '短裙'),
          T('shorts', 0, '短裤'),
          T('hot pants', 0, '热裤'),
          T('jeans', 0, '牛仔裤'),
          T('leggings', 0, '打底裤'),
          T('yoga pants', 0, '瑜伽裤'),
          T('sweatpants', 0, '运动长裤'),
          T('overalls', 0, '背带裤'),
          T('jumpsuit', 0, '连体裤'),
          T('romper', 0, '连体短裤'),
          T('nightgown', 0, '睡裙'),
          T('pajamas', 0, '睡衣'),
          T('bathrobe', 0, '浴袍'),
          T('swimsuit', 0, '泳装'),
          T('bikini', 0, '比基尼'),
          T('one-piece swimsuit', 0, '连体泳衣'),
          T('wet clothes', 1, '湿透的衣服', 1.1),
          T('transparent clothes', 2, '透明衣物', 1.2),
          T('half-undressed', 2, '脱到一半', 1.1),
          T('shirt off', 1, '脱掉上衣'),
          T('towel', 0, '毛巾'),
          T('choker', 1, '颈环'),
          T('earrings', 0, '耳环'),
          T('necklace', 0, '项链'),
          T('hair ribbon', 0, '发带蝴蝶结'),
          T('hair ornament', 0, '发饰'),
          T('hair flower', 0, '发花'),
          T('tiara', 0, '小皇冠'),
          T('lingerie', 1, '内衣（总称）'),
          T('gloves', 0, '手套'),
          T('fingerless gloves', 0, '露指手套'),
          T('arm warmers', 0, '臂套'),
          T('cap', 0, '鸭舌帽'),
          T('beanie', 0, '针织帽'),
          T('headband', 0, '发带'),
        ],
      },
      {
        key: 'action', label: '🔥 动作与体位',
        tags: [
          T('kissing', 1, '接吻'),
          T('french kiss', 1, '法式深吻', 1.1),
          T('making out', 1, '热吻缠绵'),
          T('embracing', 1, '拥抱'),
          T('cuddling', 1, '依偎'),
          T('hugging', 1, '相拥'),
          T('hugging from behind', 1, '背后抱', 1.1),
          T('breast play', 2, '玩弄胸部', 1.1),
          T('nipple play', 2, '玩弄乳头', 1.1),
          T('groping', 2, '摸胸/乱摸', 1.1),
          T('fondling', 2, '爱抚'),
          T('fingering', 3, '手指插入', 1.2),
          T('vaginal fingering', 3, '阴道指交', 1.2),
          T('clit play', 3, '玩弄阴蒂', 1.2),
          T('cunnilingus', 3, '舔阴', 1.2),
          T('oral sex', 3, '口交', 1.2),
          T('scissoring', 3, '剪刀式（磨豆腐）', 1.2),
          T('tribadism', 3, '磨蹭（摩擦式性交）', 1.2),
          T('grinding', 2, '磨蹭/摩擦', 1.1),
          T('dry humping', 2, '隔着衣服摩擦', 1.1),
          T('sixty-nine', 3, '69 式互舔', 1.2),
          T('mutual masturbation', 2, '互相自慰', 1.2),
          T('vibrator', 3, '按摩棒', 1.2),
          T('dildo', 3, '假阳具', 1.2),
          T('strap-on', 3, '穿戴式假阳具（佩带）', 1.2),
          T('penetration', 3, '插入', 1.2),
          T('cowgirl', 3, '骑乘位', 1.2),
          T('missionary', 3, '传教士体位（正常位）', 1.1),
          T('doggy style', 3, '后入式', 1.2),
          T('spooning sex', 3, '侧卧式'),
          T('standing sex', 3, '站立式'),
          T('wall sex', 3, '壁咚式做爱', 1.1),
          T('shower sex', 3, '浴室做爱', 1.1),
          T('sex', 3, '性行为（总括）', 1.2),
          T('facesitting', 3, '颜面骑乘（坐脸）', 1.2),
          T('squirting', 3, '潮吹', 1.2),
          T('orgasm', 3, '高潮', 1.2),
          T('multiple orgasms', 3, '多次高潮', 1.2),
          T('g-spot stimulation', 3, 'G 点刺激', 1.2),
          T('sweating', 1, '出汗'),
          T('wet', 2, '湿润', 1.1),
          T('dripping', 3, '液体滴落', 1.2),
        ],
      },
      {
        key: 'expression', label: '😳 表情与状态',
        tags: [
          T('ahegao', 2, '阿黑颜（失神高潮脸）', 1.2),
          T('blush', 1, '脸红'),
          T('embarrassed', 1, '害羞'),
          T('flustered', 1, '慌乱'),
          T('aroused', 1, '兴奋/动情'),
          T('lustful', 2, '充满欲望', 1.1),
          T('lewd smile', 2, '淫笑', 1.1),
          T('grinning', 1, '咧嘴笑'),
          T('smirk', 1, '坏笑'),
          T('closed eyes', 1, '闭眼'),
          T('tears', 2, '流泪', 1.1),
          T('crying in pleasure', 3, '爽哭', 1.2),
          T('drooling', 3, '流口水', 1.2),
          T('tongue out', 2, '伸舌头', 1.1),
          T('panting', 2, '喘息', 1.1),
          T('breathing heavily', 2, '粗重呼吸', 1.1),
          T('heart eyes', 1, '爱心眼'),
          T('needy', 2, '饥渴难耐', 1.1),
          T('pleading', 2, '恳求'),
          T('moaning', 3, '呻吟', 1.2),
          T('seductive smile', 1, '挑逗微笑'),
          T('surprised', 1, '惊讶'),
          T('shy', 1, '腼腆'),
          T('squirming', 2, '扭动身体', 1.1),
        ],
      },
      {
        key: 'env', label: '🌍 场景环境',
        tags: [
          T('bedroom', 0, '卧室'),
          T('bed', 0, '床上'),
          T('hotel room', 0, '酒店房间'),
          T('love hotel', 0, '情趣酒店'),
          T('bathroom', 0, '浴室'),
          T('shower', 0, '淋浴间'),
          T('bathtub', 0, '浴缸'),
          T('bubble bath', 0, '泡泡浴'),
          T('onsen', 0, '温泉'),
          T('public bath', 0, '公共浴池'),
          T('sauna', 0, '桑拿'),
          T('locker room', 0, '更衣室/储物间'),
          T('gym', 0, '健身房'),
          T('office', 0, '办公室'),
          T('classroom', 0, '教室'),
          T('library', 0, '图书馆'),
          T('dressing room', 0, '试衣间'),
          T('changing room', 0, '更衣室'),
          T('beach', 0, '海滩'),
          T('pool', 0, '泳池'),
          T('forest', 0, '森林'),
          T('rooftop', 0, '天台'),
          T('night', 0, '夜晚'),
          T('sunset', 0, '黄昏'),
          T('indoor', 0, '室内'),
          T('outdoor', 0, '室外'),
          T('japanese room', 0, '日式房间'),
          T('tatami', 0, '榻榻米'),
          T('steam', 0, '蒸汽/雾气'),
          T('desk', 0, '办公桌'),
        ],
      },
      {
        key: 'props', label: '🧰 道具与细节',
        tags: [
          T('handcuffs', 2, '手铐'),
          T('blindfold', 2, '眼罩'),
          T('collar', 2, '项圈', 1.1),
          T('leash', 2, '牵引绳', 1.1),
          T('rope', 3, '绳索（绳缚）', 1.2),
          T('mirror', 1, '镜子'),
          T('bed sheets', 0, '床单'),
          T('pillows', 0, '枕头'),
          T('rose petals', 0, '玫瑰花瓣'),
          T('candlelight', 0, '烛光'),
          T('champagne', 0, '香槟'),
          T('silk sheets', 0, '丝绸床单'),
        ],
      },
      { key: 'censor', label: '🚫 审查与码（步兵/骑兵）', tags: CENSOR_TAGS },
      { key: 'hair', label: '💇 发型', tags: HAIR_STYLES },
      { key: 'haircolor', label: '🎨 发色', tags: HAIR_COLORS },
      { key: 'view', label: '📷 视角与镜头', tags: VIEW_TAGS },
      { key: 'quality', label: '✨ 质量词', tags: QUALITY_TAGS },
    ],
  },
};

/* ---------- 场景模板 ---------- */
const TEMPLATES = {
  gay: [
    { name: '🏋️ 健身房更衣室', tags: ['1boy', '2boys', 'muscular male', 'sweat', 'towel', 'locker room', 'shirtless', 'boxer briefs', 'mutual masturbation', 'handjob', 'blush', 'panting'] },
    { name: '🏢 办公室的偷情', tags: ['1boy', '2boys', 'adult male', 'suit', 'dress shirt', 'office', 'desk', 'blowjob', 'deepthroat', 'drooling', 'messy hair'] },
    { name: '♨️ 温泉之夜', tags: ['1boy', '2boys', 'adult male', 'yukata', 'onsen', 'steam', 'naked', 'kissing', 'anal sex', 'mating press', 'moaning'] },
    { name: '🏫 教室课后', tags: ['1boy', '2boys', 'school uniform', 'classroom', 'kissing', 'handjob', 'pre-cum', 'cumshot', 'blush'] },
    { name: '🔥 Bara 写真风', tags: ['1boy', '2boys', 'bara', 'muscular male', 'hairy chest', 'jockstrap', 'speedo', 'gym', 'oil', 'glistening skin', 'seductive smile'] },
  ],
  lesbian: [
    { name: '🚿 更衣室的心跳', tags: ['1girl', '2girls', 'school uniform', 'changing room', 'locker room', 'kissing', 'groping', 'blush', 'embarrassed'] },
    { name: '♨️ 温泉之旅', tags: ['1girl', '2girls', 'yukata', 'onsen', 'steam', 'naked', 'cunnilingus', 'facesitting', 'moaning', 'squirming'] },
    { name: '🏢 办公室恋曲', tags: ['1girl', '2girls', 'office lady', 'suit', 'office', 'desk', 'fingering', 'squirming', 'orgasm', 'panting'] },
    { name: '🏖️ 海边泳装', tags: ['1girl', '2girls', 'swimsuit', 'bikini', 'beach', 'making out', 'tribadism', 'grinding', 'wet body'] },
    { name: '💜 百合新婚夜', tags: ['1girl', '2girls', 'lingerie', 'lace lingerie', 'bed', 'candlelight', 'strap-on', 'cowgirl', 'orgasm', 'moaning'] },
  ],
};
